LiveText-LiveText3.14/src/objects/Agent_Status__c.object
<CustomObject>
    <description>Agent Status</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agent Status</label>
    <nameField>
        <displayFormat>AS={0000}</displayFormat>
        <label>Agent Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Associated_Agents__c.object
<CustomObject>
    <description>Associated Agents</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <description>LiveText Number</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>Associated Agents</relationshipLabel>
        <relationshipName>Associated_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Associated_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Agents</label>
    <nameField>
        <displayFormat>Agent-{0000}</displayFormat>
        <label>Agent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <formula>Support_Number__r.Formatted_Support_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LiveText Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Number from which the SMS has been generated.</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveTextGlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Global Settings.</description>
    <fields>
        <fullName>Active_Status_Purge_Hours__c</fullName>
        <description>specify hours to change conversation header&apos;s Active status to Ended.</description>
        <label>Active Status Purge Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GlobalTriggerExecutionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GlobalTriggerExecutionEnabled if checked will enable/ disable all triggers in Organisation.</description>
        <label>GlobalTriggerExecutionEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveTextGlobalSettings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/ConsoleIntegrationControllerTest.cls
@isTest
private class ConsoleIntegrationControllerTest { 
    static LiveText_Number__c LiveTextNumber;
    static SMS_Text__c SMSText;
    static Conversation_Header__c conversationHeader;
    static User restrictedUser;
    static LiveTextGlobalSettings__c m_LiveTextGlobalSettings;
    static List<User> userList;
    static User adminUser;
    static void createAdminUser() {
        adminUser = UnitTestObjectBuilder.createAdminUser();
        insert adminUser;
    }
  
    private static void SetUp() {
        m_LiveTextGlobalSettings = new LiveTextGlobalSettings__c();
        m_LiveTextGlobalSettings.GlobalTriggerExecutionEnabled__c = true;
        m_LiveTextGlobalSettings.Active_Status_Purge_Hours__c =0;
        insert m_LiveTextGlobalSettings;
    } 
    
    static void initTestData() {
        LiveTextNumber = UnitTestObjectBuilder.createLiveTextNumber();
        insert LiveTextNumber;
        userList = new List<User>();
        for(Integer i=0; i<2; i++) {
            userList.add(UnitTestObjectBuilder.createAdminUser());
        }
        insert userList;
        UnitTestObjectBuilder.assignPermissionSetToUsers(userList);
        List<Associated_Agents__c> associatedAgentList = new List<Associated_Agents__c>();
        for(User usr : userList){
            associatedAgentList.add(UnitTestObjectBuilder.createAssociatedAgent(LiveTextNumber.Id, usr.Id));
        }
        insert associatedAgentList;
        SMSText = UnitTestObjectBuilder.CreateSMSTextRecord(LiveTextNumber, null);
        insert SMSText;
        SMSText =   [   SELECT Id, Conversation_Header__c 
                        FROM SMS_Text__c 
                        WHERE Id=:SMSText.Id
                    ];
        conversationHeader = Util.getCurrentConversationHeaderList(SMSText.Conversation_Header__c)[0]; 
        restrictedUser = UnitTestObjectBuilder.createRestrictedUser();
    }

    static testMethod void ConsoleIntegrationController_Test() {
        createAdminUser();
        system.runAs(adminUser) {       
            test.StartTest();
            SetUp();
            initTestData();
            ApexPages.StandardController sc = new ApexPages.StandardController(conversationHeader);
            ConsoleIntegrationController cic = new ConsoleIntegrationController(sc);
            cic.getLiveTextRecordSize();
            System.assertEquals(cic.getUserLocale(),'en_US');
            System.assertEquals(cic.totalSize, 1);
            String nameSpace = cic.nameSpace;
            String conversationSessionPrefix = cic.conversationSessionPrefix;
            System.assertNotEquals(conversationSessionPrefix, null);
            String LeadSource = cic.LeadSource;
            System.assertNotEquals(LeadSource, null);
            
            String keyPrefix = cic.keyPrefix;
            String formattedOriginatingNumber = cic.formattedOriginatingNumber;
            String openPrimaryTabName = cic.openPrimaryTabName;
            String autoResponseMessage = cic.autoResponseMessage;
            List < Conversation_Header__c > conversationHeaderListProp = cic.conversationHeaderList;
            List<LiveText_Number__c> phoneNumbers = cic.phoneNumbers;
            String MyPhoneNumbers = cic.MyPhoneNumbers;
            List < Conversation_Header__c > conversationHeaderList = cic.getConversationHeaderList();
            ConsoleIntegrationController.getPhoneNumberAccounts('+12125551212');
            ConsoleIntegrationController.getPhoneNumberContacts('+12125551212');
            ConsoleIntegrationController.getPhoneNumberLeads('+12125551212');
                                  
            cic.conversationHeaderId = conversationHeader.Id;
            PageReference pageRef;
            pageRef = cic.getConversationHeaderRecords();
            System.assertEquals(pageRef, null);
            cic.conversationHeaderId = conversationHeader.Id;
            ConsoleIntegrationController.AcceptRemote(cic.conversationHeaderId);
            ConsoleIntegrationController.isConversationHeaderActive(conversationHeader.Id);
            ConsoleIntegrationController.isNewConversationHeader(conversationHeader.Id);
            ConsoleIntegrationController.GetRelatedObjectsAndAutoLink(Util.getCurrentConversationHeaderList(conversationHeader.Id).get(0),'+16175551212', new List<SObjectWrapper>());
            
            ConsoleIntegrationController.getCustomLogo('test', 'test');
            ConsoleIntegrationController.dummyRemoteAction();
            LiveText_Number__c LiveTextNumberObj = UnitTestObjectBuilder.createLiveTextNumber();
            Insert LiveTextNumberObj;
            
            String userStatus = cic.getCurrentUserStatus();
            String convPrefix1 = cic.getConversationSessionPrefix();
            String buildUrl = cic.buildUrl('myPrefix');
            String leadSourceVal = ConsoleIntegrationController.findLeadSourceVal();
             
            List < SelectOption > items = cic.getItems();
            System.assertNotEquals(items, null);
            String status = cic.status;
            String jsonStr = cic.currentConversationHeader;
            System.assertNotEquals(jsonStr, null);
            List<SMS_Text__c> smsList = ConsoleIntegrationController.getSMSMessages(conversationHeader.Id);
            system.assert(smsList != null);
            system.assert(!smsList.isEmpty());
            test.stopTest();
        }
    }


    static testMethod void Test_UpdateAgentStatus_Positive() {
        createAdminUser();
        system.runAs(adminUser){
            Test.startTest();
            SetUp() ;
            initTestData();
            ApexPages.StandardController sc = new ApexPages.StandardController(conversationHeader);
            ConsoleIntegrationController cic = new ConsoleIntegrationController(sc);
            String status = cic.status;
            system.assertEquals(status, Constant.STATUS_OFFLINE);
            cic.updateAgentStatus();
            Agent_Status__c agentStatus = [Select Id From Agent_Status__c Where User__c=:UserInfo.getUserId()];
            system.assert(agentStatus != null);
            system.assert(agentStatus.Id != null);
            cic.status = null;
            status = cic.status;
            system.assertEquals(status, Constant.STATUS_OFFLINE );
            status = Constant.STATUS_AVAIALBLE;
            cic.updateAgentStatus();
            Test.stopTest();
        }
    }
    
    static testMethod void Test_UpdateAgentStatus_Negative() {
        createAdminUser();
        system.runAs(adminUser){
            Test.startTest();
            SetUp() ;
            initTestData();
            ApexPages.StandardController sc = new ApexPages.StandardController(conversationHeader);
            ConsoleIntegrationController cic = new ConsoleIntegrationController(sc);
            system.runAs(restrictedUser){
                String status = cic.status;
                system.assertNotEquals(status, Constant.STATUS_AVAIALBLE);
                try {
                    cic.updateAgentStatus();
                } 
                catch (Exception ex) {
                    system.assertEquals(ex.getTypeName(), AccessController.CRUDException.class.getName());
                }
                List<Agent_Status__c> agentStatus = [Select Id From Agent_Status__c Where User__c=:UserInfo.getUserId()];
                system.assert(agentStatus != null);
                system.assert(agentStatus.isEmpty());
            }
            Test.stopTest();
        }
    }
    
    static testMethod void Test_IsRoutedToCurrentUser_Positive() {
        createAdminUser();
        system.runAs(adminUser){
            Test.startTest();
            SetUp() ;
            initTestData();
            system.runAs(userList.get(0)){
                Boolean isRouted = ConsoleIntegrationController.isRoutedToCurrentUser(LiveTextNumber.Id);
                system.assert(isRouted);
                system.assert(ConsoleIntegrationController.isConversationRoutedToCurrentUser((String)conversationHeader.get('Originating_Number__c'), (String) LiveTextNumber.Id));
            }
            Test.stopTest();
        }
    }
    
    static testMethod void Test_EndConversation_Negative() {
        createAdminUser();
        system.runAs(adminUser){
            Test.startTest();
            SetUp() ;
            initTestData();
            system.runAs(userList.get(0)){
                ConsoleIntegrationController.endChat('123');
            }
            Test.stopTest();
        }
    }   
}