LiveText-LiveText3.14/src/objects/Associated_Agents__c.object
<CustomObject>
    <description>Associated Agents</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <description>LiveText Number</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>Associated Agents</relationshipLabel>
        <relationshipName>Associated_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Associated Agents</label>
    <nameField>
        <displayFormat>Agent-{0000}</displayFormat>
        <label>Agent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <formula>Support_Number__r.Formatted_Support_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LiveText Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveTextGlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Global Settings.</description>
    <fields>
        <fullName>Active_Status_Purge_Hours__c</fullName>
        <description>specify hours to change conversation header&apos;s Active status to Ended.</description>
        <label>Active Status Purge Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GlobalTriggerExecutionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GlobalTriggerExecutionEnabled if checked will enable/ disable all triggers in Organisation.</description>
        <label>GlobalTriggerExecutionEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveTextGlobalSettings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/LiveTextControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LiveTextControllerTest {

  static LiveText_Number__c LiveTextNumber;
	static SMS_Text__c SMSText;
	static Conversation_Header__c conversationHeader;
	static User restrictedUser;
	static LiveTextGlobalSettings__c m_LiveTextGlobalSettings;
	static List<User> userList;
	static User adminUser;
	
	static void createAdminUser(){
    	adminUser = UnitTestObjectBuilder.createAdminUser();
    	insert adminUser;
    }
  
	private static void SetUp() {
		m_LiveTextGlobalSettings = new LiveTextGlobalSettings__c();
		m_LiveTextGlobalSettings.GlobalTriggerExecutionEnabled__c = true;
		m_LiveTextGlobalSettings.Active_Status_Purge_Hours__c =0;
		insert m_LiveTextGlobalSettings;
	} 
	
	static void initTestData(){
		LiveTextNumber = UnitTestObjectBuilder.createLiveTextNumber();
		insert LiveTextNumber;
        userList = new List<User>();
        for(Integer i=0; i<2; i++){
            userList.add(UnitTestObjectBuilder.createAdminUser());
        }
        insert userList;
        UnitTestObjectBuilder.assignPermissionSetToUsers(userList);
		
        List<Associated_Agents__c> associatedAgentList = new List<Associated_Agents__c>();
        for(User usr : userList){
        	associatedAgentList.add(UnitTestObjectBuilder.createAssociatedAgent(LiveTextNumber.Id, usr.Id));
        }
        insert associatedAgentList;
        
        
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        conversationHeader = UnitTestObjectBuilder.CreateOutboundConversationHeader(phoneNumber, LiveTextNumber.Id);                    
        insert conversationHeader;
               
 		restrictedUser = UnitTestObjectBuilder.createRestrictedUser();
    }
    
	static testMethod void LiveTextController_Test() {
    	createAdminUser();
    	system.runAs(adminUser){		
			test.StartTest();
			//SetUp() ;
			initTestData();
			ApexPages.StandardController sc = new ApexPages.StandardController(conversationHeader);
			LiveTextController ltcc = new LiveTextController(sc);
			
			ltcc.init();
			ltcc.getCurrentConversationHeaderList();
			LiveTextController.getMessagePayloadResponse('', 0, '', '', '');
			LiveTextController.getSMSTextRecord('');
			LiveTextController.createSMSTextRecord('','');
			LiveTextController.sendSMS2(null,'');

			List<SMS_Text__c> smsList = ConsoleIntegrationController.getSMSMessages(conversationHeader.Id);
			system.assert(smsList != null);
			system.assert(ltcc.source != null);
			system.assert(ltcc.liveText != null);
			system.assert(ltcc.nameSpace != null);
     		system.assert(ltcc.userName != null);
			system.assert(ltcc.ConversationHeaderRecords != null);
			test.stopTest();
    	}
	}

	static testMethod void LiveTextController_Test_Ended() {
    	createAdminUser();
    	system.runAs(adminUser){		
			test.StartTest();
			//SetUp() ;
			initTestData();
			conversationHeader.Status__c = constant.stage_ended;
			update conversationHeader;
			ApexPages.StandardController sc = new ApexPages.StandardController(conversationHeader);
			LiveTextController ltcc = new LiveTextController(sc);

			ltcc.init();
	
			test.stopTest();
    	}
	}
}