LiveText-LiveText3.14/src/objects/Campaign_Send__c.object
<CustomObject>
    <description>The Campaign Send object represents a single instance of sending a campaign using the Send Text to Campaign Members button. This object will contain the attributes of the Send as configured by the user.</description>
    <fields>
        <fullName>ErrorStatus__c</fullName>
        <description>Campaign Member status if message is not successfully sent or member is deemed a duplicate.</description>
        <inlineHelpText>Campaign Member status if message is not successfully sent or member is deemed a duplicate.</inlineHelpText>
        <label>ErrorStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OptoutStatus__c</fullName>
        <description>Campaign Member status if member opts out.</description>
        <inlineHelpText>Campaign Member status if member opts out.</inlineHelpText>
        <label>OptoutStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResponseStatus__c</fullName>
        <description>Campaign Member status if member responds.</description>
        <inlineHelpText>Campaign Member status if member responds.</inlineHelpText>
        <label>ResponseStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuccessStatus__c</fullName>
        <description>Campaign Member status if message is successfully sent.</description>
        <inlineHelpText>Campaign Member status if message is successfully sent.</inlineHelpText>
        <label>SuccessStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Campaign Send</label>
    <nameField>
        <label>Campaign Send Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CampaignSends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Campaign_Send_Member__c.object
<CustomObject>
    <description>The Campaign Send Member object represents a member of a Send.</description>
    <fields>
        <fullName>CampaignMemberId__c</fullName>
        <description>Id of the Campaign Member.</description>
        <inlineHelpText>Id of the Campaign Member.</inlineHelpText>
        <label>CampaignMemberId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignSend__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the CampaignSend.</description>
        <inlineHelpText>Lookup to the CampaignSend.</inlineHelpText>
        <label>CampaignSend</label>
        <referenceTo>Campaign_Send__c</referenceTo>
        <relationshipLabel>CampaignSendMembers</relationshipLabel>
        <relationshipName>CampaignSendMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Campaign Send Member</label>
    <nameField>
        <label>Campaign Send Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CampaignSendMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Recent_Campaign_Send_Member__c.object
<CustomObject>
    <description>The Recent Campaign Send Member object will be created in order to properly track what message a member may be responding to. The  purpose of this object is to track the most recent Campaign between a given LiveText number and a phone number.</description>
    <fields>
        <fullName>CampaignSendMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Campaign Send Member.</description>
        <inlineHelpText>Lookup to the Campaign Send Member.</inlineHelpText>
        <label>CampaignSendMember</label>
        <referenceTo>Campaign_Send_Member__c</referenceTo>
        <relationshipLabel>RecentCampaignSendMembers</relationshipLabel>
        <relationshipName>RecentCampaignSendMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Recent Campaign Send Member</label>
    <nameField>
        <label>Recent Campaign Send Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RecentCampaignSendMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/UpdateCampaignMemberStatusAction.cls
global class UpdateCampaignMemberStatusAction {
	@InvocableMethod(label='Update Campaign Member Status' description='Update Campaign Member base on Response Status')
	global static  void updateCampaignMemberStatus(List<CampaignMemberUpdateStatus> items) {
		/**
		* Change List of CampaignMemberUpdateStatus to the Map<CampaignMemberId, Status>
		*/
		Map<Id, String> campaignMemberResponseTypeMap = new Map<Id, String>();
		Map<Id, String> newCampaignMemberStatusMap = new Map<Id, String>();
		List<CampaignMember> updateCampaignMemberList = new List<CampaignMember>();
		for(CampaignMemberUpdateStatus item:items) 
		{
			if(item.responseType != NULL && item.campaignMemberId != NULL) 
			{
				campaignMemberResponseTypeMap.put(item.campaignMemberId, item.responseType);
			}
		}
		List<Campaign_Send_Member__c> campaignSendMemberList = new List<Campaign_Send_Member__c>();
		if(!campaignMemberResponseTypeMap.isEmpty()) 
		{
			campaignSendMemberList =	[	SELECT 	Id, CampaignSend__c, CampaignMemberId__c,
													CampaignSend__r.ErrorStatus__c, CampaignSend__r.OptoutStatus__c,
													CampaignSend__r.ResponseStatus__c, CampaignSend__r.SuccessStatus__c
											FROM 	Campaign_Send_Member__c
											WHERE 	Id IN :campaignMemberResponseTypeMap.keySet() AND CampaignSend__c != NULL
											LIMIT 	50000];
			if(campaignSendMemberList != NULL) 
			{
				for(Campaign_Send_Member__c item :campaignSendMemberList) 
				{
					if(item.CampaignMemberId__c != NULL) {
						String responseType = campaignMemberResponseTypeMap.get(item.Id);
						if(responseType == Label.CampaignResponseTypeResponded && !String.isBlank(item.CampaignSend__r.ResponseStatus__c)) 
						{
							newCampaignMemberStatusMap.put(item.CampaignMemberId__c, item.CampaignSend__r.ResponseStatus__c);
						}
						else if(responseType == Label.CampaignResponseTypeOptOut && !String.isBlank(item.CampaignSend__r.OptoutStatus__c)) 
						{
							newCampaignMemberStatusMap.put(item.CampaignMemberId__c, item.CampaignSend__r.OptoutStatus__c);
						}
					}
				}
			}
			if(!newCampaignMemberStatusMap.isEmpty()) 
			{
				for(CampaignMember item :	[	SELECT Id, Status
												FROM CampaignMember
												WHERE Id IN:newCampaignMemberStatusMap.keySet()]) 
				{
					String status =  newCampaignMemberStatusMap.get(item.Id);
					item.Status = newCampaignMemberStatusMap.get(item.Id);
					updateCampaignMemberList.add(item);
				}
			}
			if(!updateCampaignMemberList.isEmpty())
			{
				try 
				{
					AccessController.updateAsSystem(updateCampaignMemberList);
				} 
				catch(Exception ex) 
				{
                    Util.insertException('updateCMStatus', constant.priority_high, ex.getMessage());
                } 
			}
		}
		
		// Delete all recent campaign members that were just processed
		if(!campaignMemberResponseTypeMap.isEmpty())
		{
			List<Recent_Campaign_Send_Member__c> recentCampaignSendMemberList = [	SELECT 	Id
											FROM 	Recent_Campaign_Send_Member__c
											WHERE 	CampaignSendMember__r.Id IN :campaignMemberResponseTypeMap.keySet()
											LIMIT 	50000];
			if(!recentCampaignSendMemberList.isEmpty())
			{
				try 
				{
					AccessController.deleteAsSystem(recentCampaignSendMemberList);
				} 
				catch(Exception ex) 
				{
                    Util.insertException('updateCMStatus', constant.priority_high, ex.getMessage());
                } 
			}
		}
	}

}