LiveText-LiveText3.14/src/objects/Campaign_Send__c.object
<CustomObject>
    <description>The Campaign Send object represents a single instance of sending a campaign using the Send Text to Campaign Members button. This object will contain the attributes of the Send as configured by the user.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Campaign associated with this Send</description>
        <inlineHelpText>Lookup to the Campaign associated with this Send</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>CampaignSends</relationshipLabel>
        <relationshipName>CampaignSends</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OptoutStatus__c</fullName>
        <description>Campaign Member status if member opts out.</description>
        <inlineHelpText>Campaign Member status if member opts out.</inlineHelpText>
        <label>OptoutStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResponseStatus__c</fullName>
        <description>Campaign Member status if member responds.</description>
        <inlineHelpText>Campaign Member status if member responds.</inlineHelpText>
        <label>ResponseStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupportNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The number to send messages from</description>
        <inlineHelpText>The number to send messages from</inlineHelpText>
        <label>SupportNumber</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>CampaignSends</relationshipLabel>
        <relationshipName>CampaignSends</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Campaign Send</label>
    <nameField>
        <label>Campaign Send Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CampaignSends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Campaign_Send_Member__c.object
<CustomObject>
    <description>The Campaign Send Member object represents a member of a Send.</description>
    <fields>
        <fullName>CampaignMemberId__c</fullName>
        <description>Id of the Campaign Member.</description>
        <inlineHelpText>Id of the Campaign Member.</inlineHelpText>
        <label>CampaignMemberId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignSend__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the CampaignSend.</description>
        <inlineHelpText>Lookup to the CampaignSend.</inlineHelpText>
        <label>CampaignSend</label>
        <referenceTo>Campaign_Send__c</referenceTo>
        <relationshipLabel>CampaignSendMembers</relationshipLabel>
        <relationshipName>CampaignSendMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Preferred phone number from Campaign Member.</description>
        <inlineHelpText>Preferred phone number from Campaign Member.</inlineHelpText>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Campaign Send Member</label>
    <nameField>
        <label>Campaign Send Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CampaignSendMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Business support hours for this phone number. Business Hours can be managed via Setup.</inlineHelpText>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipLabel>LiveText Numbers</relationshipLabel>
        <relationshipName>LiveText_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A number must be verified by HeyWire Business before it is enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Validated</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/UpdateCampaignMemberStatusActionTest.cls
@isTest
private class UpdateCampaignMemberStatusActionTest
{

	static CampaignMemberStatus createStatus(String campId, String label, Boolean isDefault, Boolean responded, Integer i){
        CampaignMemberStatus cs = new CampaignMemberStatus();
        cs.CampaignId = campId;
        cs.Label = label;
        cs.IsDefault = isDefault;
        cs.HasResponded = responded;
        cs.SortOrder = i;
        return cs;
  }

	@testSetup
	static void baseTestSetup()
	{
		/*
		* Creat Account
		*/
		Account newAccount = new Account();
		newAccount.Name = 'MyAccount';
		insert newAccount;
		/*
		* Creat Contacts
		*/
		List<Contact> insertNewContactsList = new List<Contact>();
		for(integer i = 0; i < 10; i++)
		{
			Contact newContact = new Contact();
			newContact.FirstName = 'MyContact'+i;
			newContact.LastName = 'MyContact'+i;
			insertNewContactsList.add(newContact);
		}
		insert insertNewContactsList;
		/*
		* Create Campaign
		*/
		Campaign newCampaign = new Campaign();
		newCampaign.Description = '123';
		newCampaign.Name = 'myCamp';
		insert newCampaign;
		/*
		* Creat CampaignMemberStatus
		*/
		CampaignMemberStatus insertResponedStatus = UpdateCampaignMemberStatusActionTest.createStatus(newCampaign.Id, Label.CampaignResponseTypeResponding, TRUE, TRUE, 11);
		CampaignMemberStatus insertOptOutStatus = UpdateCampaignMemberStatusActionTest.createStatus(newCampaign.Id, Label.CampaignResponseTypeOptOut, FALSE, TRUE, 10);
		List<CampaignMemberStatus> insertStatusList = new List<CampaignMemberStatus>();
		insertStatusList.add(insertResponedStatus);
		insertStatusList.add(insertOptOutStatus);
		insert insertStatusList;
		/*
		* Add Campaign Members to Campaign
		*/
		List<CampaignMember> insertNewCampaignMembersList = new List<CampaignMember>();
		for(Contact item:insertNewContactsList)
		{
			CampaignMember newCampaignMember = new CampaignMember();
			newCampaignMember.ContactId = item.Id;
			newCampaignMember.CampaignId = newCampaign.Id;
			insertNewCampaignMembersList.add(newCampaignMember);
		}
		insert insertNewCampaignMembersList;
		/*
		* Fet Default BusinessHours
		*/
		BusinessHours defaultBussinesHours = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
		/*
		* Create Live Text Number
		*/
		LiveText_Number__c newLiveTextNumber = new LiveText_Number__c();
		newLiveTextNumber.Name = 'Short Code 5 Digits Test';
		newLiveTextNumber.Number__c = '71717';
		newLiveTextNumber.Validated__c = TRUE;
		newLiveTextNumber.Business_Hours__c = defaultBussinesHours.Id;
		insert newLiveTextNumber;
		/*
		* Create Campaign Send
		*/
		Campaign_Send__c newCampaignSend = new Campaign_Send__c();
		newCampaignSend.Campaign__c = newCampaign.Id;
		newCampaignSend.SupportNumber__c = newLiveTextNumber.Id;
		newCampaignSend.ResponseStatus__c =  Label.CampaignResponseTypeResponding;
		newCampaignSend.OptoutStatus__c = Label.CampaignResponseTypeOptOut;
		insert newCampaignSend;
		/*
		* Create Campaign Send Members
		*/
		List<Campaign_Send_Member__c> insertCampaignSendMembersList = new List<Campaign_Send_Member__c>();
		for(CampaignMember item:insertNewCampaignMembersList)
		{
			Campaign_Send_Member__c newCampaignSendMember = new Campaign_Send_Member__c();
			newCampaignSendMember.CampaignMemberId__c = (String)item.Id;
			newCampaignSendMember.CampaignSend__c = newCampaignSend.Id;
			newCampaignSendMember.Phone__c = '73737';
			insertCampaignSendMembersList.add(newCampaignSendMember);
		}
		insert insertCampaignSendMembersList;
	}

	@isTest
	static void itShouldUpdateCampaignMemberStatus()
	{
		List<CampaignMemberUpdateStatus> newCampaignMemberStatusList = new List<CampaignMemberUpdateStatus>();
		for(Campaign_Send_Member__c item:[SELECT Id, CampaignMemberId__c FROM Campaign_Send_Member__c])
		{
			CampaignMemberUpdateStatus newCampaignMemberItem = new CampaignMemberUpdateStatus();
			newCampaignMemberItem.campaignMemberId = item.Id;
			newCampaignMemberItem.responseType = Label.CampaignResponseTypeResponding;
			newCampaignMemberStatusList.add(newCampaignMemberItem);
		}
		newCampaignMemberStatusList[0].responseType = Label.CampaignResponseTypeOptOut;
		Test.startTest();
		UpdateCampaignMemberStatusAction.updateCampaignMemberStatus(newCampaignMemberStatusList);
		Test.stopTest();
		List<CampaignMember> checkCampaignMembersList = new List<CampaignMember>([SELECT Id, Status FROM CampaignMember WHERE Status =:Label.CampaignResponseTypeOptOut]);
		System.AssertEquals(Label.CampaignResponseTypeOptOut, checkCampaignMembersList.get(0).Status);
		checkCampaignMembersList = new List<CampaignMember>([SELECT Id, Status FROM CampaignMember WHERE Status =:Label.CampaignResponseTypeResponding]);
		System.AssertEquals(Label.CampaignResponseTypeResponding, checkCampaignMembersList.get(0).Status);
	}
}