LiveText-LiveText3.14/src/objects/Campaign_Send_Member__c.object
<CustomObject>
    <description>The Campaign Send Member object represents a member of a Send.</description>
    <fields>
        <fullName>FromNumber__c</fullName>
        <description>Formula to CampaignSend Support Number.</description>
        <formula>CampaignSend__r.SupportNumber__r.Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula to CampaignSend Support Number.</inlineHelpText>
        <label>FromNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Preferred phone number from Campaign Member.</description>
        <inlineHelpText>Preferred phone number from Campaign Member.</inlineHelpText>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Campaign Send Member</label>
    <nameField>
        <label>Campaign Send Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CampaignSendMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>AcceptedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who accepted the conversation.</description>
        <label>Accepted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Text_Session_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ConversationReopened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate whether conversation is re-opened or not by default this is set to false</description>
        <label>ConversationReopened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ConversationType__c</fullName>
        <label>ConversationType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndedTime__c</fullName>
        <description>Records the time that a text session was ended</description>
        <inlineHelpText>Records the time that a text session was ended</inlineHelpText>
        <label>EndedTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <formula>Support_Number__r.Formatted_Support_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LiveText Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessagePreview__c</fullName>
        <label>MessagePreview</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Number from which the SMS has been generated.</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SessionReopenedTime__c</fullName>
        <description>Records the time that a text session is re-opened</description>
        <inlineHelpText>Records the time that a text session is re-opened</inlineHelpText>
        <label>SessionReopenedTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support number that is LiveText enabled.</description>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/ITR_Message__c.object
<CustomObject>
    <description>Inbound Messages for ITR</description>
    <fields>
        <fullName>Available_Agents__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Agents</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Campaign_Send_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Campaign Send Member.</description>
        <inlineHelpText>Lookup to the Campaign Send Member.</inlineHelpText>
        <label>Campaign Send Member</label>
        <referenceTo>Campaign_Send_Member__c</referenceTo>
        <relationshipLabel>ITR Messages</relationshipLabel>
        <relationshipName>ITR_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HTML_Transcript__c</fullName>
        <description>HTML transcript for this interaction</description>
        <label>HTML Transcript</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Within_Business_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the current message was received during business hours</description>
        <label>Is Within Business Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>LiveText Number associated with this interaction</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>ITR Messages</relationshipLabel>
        <relationshipName>ITR_Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message associated with this interaction</description>
        <label>Message</label>
        <length>480</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mo_Message_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MO Message Counter is incremented by 1 every time a Mobile Originated message is received by the ITR.</description>
        <inlineHelpText>MO Message Counter is incremented by 1 every time a Mobile Originated message is received by the ITR.</inlineHelpText>
        <label>Mo Message Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opt_In_Status__c</fullName>
        <description>Opt-in status at time of this interaction</description>
        <label>Opt-In Status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating phone number for this interaction</description>
        <label>Originating Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Transcript__c</fullName>
        <description>Text transcript for this interaction</description>
        <label>Text Transcript</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ITR Message</label>
    <nameField>
        <label>ITR Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITR Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Notify_Users_During_Off_Hours__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>When checked, new text sessions received during off hours will populate the user&apos;s (or agent&apos;s) notification queue.</inlineHelpText>
        <label>Notify Users during off hours?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text_Session_Reuse_Time_seconds__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The time between when a text session is ended and a new text message is received that an existing text session should be reused.</inlineHelpText>
        <label>Text Session Reuse Time (seconds)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveTextGlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Global Settings.</description>
    <fields>
        <fullName>GlobalTriggerExecutionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GlobalTriggerExecutionEnabled if checked will enable/ disable all triggers in Organisation.</description>
        <label>GlobalTriggerExecutionEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveTextGlobalSettings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/Recent_Campaign_Send_Member__c.object
<CustomObject>
    <description>The Recent Campaign Send Member object will be created in order to properly track what message a member may be responding to. The  purpose of this object is to track the most recent Campaign between a given LiveText number and a phone number.</description>
    <fields>
        <fullName>CampaignSendMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Campaign Send Member.</description>
        <inlineHelpText>Lookup to the Campaign Send Member.</inlineHelpText>
        <label>CampaignSendMember</label>
        <referenceTo>Campaign_Send_Member__c</referenceTo>
        <relationshipLabel>RecentCampaignSendMembers</relationshipLabel>
        <relationshipName>RecentCampaignSendMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Recent Campaign Send Member</label>
    <nameField>
        <label>Recent Campaign Send Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RecentCampaignSendMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>480</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LiveText</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/SMSTextTriggerHandler.cls
public with sharing class SMSTextTriggerHandler extends TriggerManager.TriggerHandler {
    
   private Semaphore sem = new Semaphore(constant.SEMAPHORE_SMS_TEXT_TRIGGER_HANDLER);

   /**
    * @description Checks if new sms text is received within business hours or not. If not then 
    *               sends the offline hours message to customer and sets the text session header to offline.
    * @param List of new SMS text records.
    * @param Map of new SMS text records.
    */
   public override void onAfterInsert(List<SObject> newRecords, Map<Id, SObject> newRecordsMap) {
        if(Constant.on_after_insert_smstext_trg == true){
            Constant.on_after_insert_smstext_trg = false;
            afterInsertUpdate((List<SMS_Text__c>) newRecords, (Map<Id, SMS_Text__c>) newRecordsMap, null);
            sem.Release();
        }
    }
    
    /**
     * @description Associate the existing conversation header with incoming SMS Text record
     *              -- Create new conversation header if not found and associate it with the incoming SMS Text
     * @param List of new SMS text records.
     */
    public override void onBeforeInsert(List<SObject> newRecords){
        if(sem.Acquire()){
            if (Constant.on_before_insert_smstext_trg == true) {
                Constant.on_before_insert_smstext_trg = false;
                beforeInsert((List<SMS_Text__c> ) newRecords);
            }
        }
    }
    
    private String getKey(SMS_Text__c sms){
        return sms.Originating_Number__c + '-' + sms.Support_Number__c;
    }
    
    private String getKey(Conversation_Header__c ch){
        return ch.Originating_Number__c + '-' + ch.Support_Number__c;
    }
    
    private void beforeInsert(List<SMS_Text__c> newSmsTexList){
        try {
            SMSTextListRoutingInfo routingInfo = null;
            Map<String, List<SMS_Text__c>> smsWithoutConvHeaderMap = new Map<String, List<SMS_Text__c>>();
            Boolean triggerExecutionEnabled = false;
            LiveTextGlobalSettings__c gblSettings = Util.getLiveTextGlobalSettings();
            List<Conversation_Header__c> newConversationHeaderList = new List<Conversation_Header__c>();
            Map<String, Id> smsOriginSupportToConversationHeader = new Map<String, Id>();
            
            Map<String,Datetime> conversationHeaderTimeMap = new Map<String,Datetime>();
            List<Conversation_Header__c> updateStatusToNewList = new List<Conversation_Header__c>();
            Map<String,Conversation_Header__c> updateChHeaderStatusNewMap = new Map<String,Conversation_Header__c>();
            Map<String,Datetime> smsTextTimeMap = new Map<String,Datetime>();
            Map<String,SMS_Text__c> smsTextMap = new Map<String,SMS_Text__c>();
            Set<String> smsSupportNumbers = new Set<String>();
            
            if(gblSettings != null){
                if(gblSettings.GlobalTriggerExecutionEnabled__c != null){
                    triggerExecutionEnabled = gblSettings.GlobalTriggerExecutionEnabled__c;
                }
            }
            if(triggerExecutionEnabled){
                // Create set of incoming SMS Originiating Numbers to limit SOQL query
                Set<String> smsOriginatingNumbers = new Set<String>();
                for(SMS_Text__c sms : newSmsTexList){
                    smsOriginatingNumbers.add(sms.Originating_Number__c);
                    //LT-1274 smsTextTimeMap is the map that contains sms orginating number and support number and the time of the sms
                    smsSupportNumbers.add(sms.Support_Number__c);
                    if(sms.Source__c == 'LiveText'){
                        smsTextTimeMap.put(getKey(sms),System.now());
                        smsTextMap.put(getKey(sms),sms);
                    }
                }
                //Lt-1274
                //Get the configured text session reuse time from LiveTextNumer__C object
                Map<String,Integer> reuseTimeMap = new Map<String,Integer>();
                Integer maxReuseTime = 0; 
                for(LiveText_Number__c l : [SELECT ID,Number__c,Text_Session_Reuse_Time_seconds__c FROM LiveText_Number__c WHERE Id IN :smsSupportNumbers]){
                    if(l.Text_Session_Reuse_Time_seconds__c != null){
                        //Map that contains live text number id and its associated reuse time
                        reuseTimeMap.put(l.Id,Integer.valueOf(l.Text_Session_Reuse_Time_seconds__c));
                        maxReuseTime = Math.max(maxReuseTime, Integer.valueOf(l.Text_Session_Reuse_Time_seconds__c));
                    }
                }
                if(!newSmsTexList.isEmpty()){
                    // process smstext records whose conversation Id is null and has possibility of matching Support_Number__c and Originating_Number__c
                    // with existing conversations header record.
                    for(Conversation_Header__c ch : [SELECT Status__c, Originating_Number__c, Support_Number__c,MessagePreview__c
                                                        FROM Conversation_Header__c 
                                                        WHERE Status__c != :Constant.stage_ended 
                                                            AND Status__c != :Constant.stage_offline 
                                                            AND Originating_Number__c IN :smsOriginatingNumbers 
                                                        ORDER BY LastModifiedDate DESC
                                                        LIMIT 1000]){
                        smsOriginSupportToConversationHeader.put(getKey(ch), ch.Id);
                    }
                    if(!smsTextTimeMap.isEmpty() && maxReuseTime > 0){
                        //Lt-1274 Get the recently ended conversation headers of the day
                        Set<Conversation_Header__c> distinctChList = new Set<Conversation_Header__c>();
                        Map<String,String> timeMap = new Map<String,String>();
                        Map<String,Conversation_Header__c> conversationMap = new Map<String,Conversation_Header__c>();
                        for(Conversation_Header__c rechl : [SELECT Status__c, Originating_Number__c, Support_Number__c,MessagePreview__c,EndedTime__c,ConversationReopened__c
                                                                FROM Conversation_Header__c
                                                                WHERE Status__c = :Constant.stage_ended 
                                                                    AND Originating_Number__c IN :smsOriginatingNumbers 
                                                                    AND Support_Number__c IN :smsSupportNumbers 
                                                                    AND EndedTime__c > :System.Now().addSeconds(-maxReuseTime) 
                                                                    AND ConversationReopened__c = :false
                                                                ORDER BY LastModifiedDate DESC, Originating_Number__c ASC
                                                                LIMIT 10000]){

                            conversationHeaderTimeMap.put(getKey(rechl), rechl.EndedTime__c);
                            timeMap.put(getKey(rechl),rechl.Support_Number__c);
                            conversationMap.put(getKey(rechl),rechl);
                        }
                        
                        for(String cht : conversationHeaderTimeMap.keySet()){
                            Date conversationDate = conversationHeaderTimeMap.get(cht).date();
                            Date smsTextDate = smsTextTimeMap.get(cht).date();
                            if(smsTextDate.isSameDay(conversationDate)){
                                Long seconds = (smsTextTimeMap.get(cht).getTime() - conversationHeaderTimeMap.get(cht).getTime())/1000;
                                if(seconds <= reuseTimeMap.get(timeMap.get(cht))){
                                    if(smsOriginSupportToConversationHeader.get(cht) == null){
                                        smsOriginSupportToConversationHeader.put(cht, conversationMap.get(cht).Id);
                                        //filtering the recently ended conversation list based on the configures reuse time.
                                        distinctChList.add(conversationMap.get(cht));
                                    }
                                }
                            }
                        }
                        if(!distinctChList.isEmpty()){
                            //Reopening the conversation header; distinctChList has no nulls
                            for(Conversation_Header__c ch : distinctChList){
                                ch.Status__c = Constant.stage_new;
                                String smsMessage = smsTextMap.get(getKey(ch)).Message__c;
                                if(!String.isBlank(smsMessage)){
                                    if(smsMessage.length() >= 255){
                                        ch.MessagePreview__c = smsMessage.substring(0,255);
                                    }else{
                                        ch.MessagePreview__c = smsMessage;
                                    }
                                }
                                ch.ConversationReopened__c = true;
                                ch.SessionReopenedTime__c = system.now();
                                ch.AcceptedBy__c = null;
                                updateStatusToNewList.add(ch);
                                updateChHeaderStatusNewMap.put(getKey(ch),ch);        
                            }
                        }
                    }

                    List<Conversation_Header__c> updateMessagePreview = new List<Conversation_Header__c>();
                    Set<Id> chIdtoRetrieve = new Set<Id>();
                    for(SMS_Text__c sms : newSmsTexList){
                        Id chId = smsOriginSupportToConversationHeader.get(getKey(sms));
                        if(chId != null){
                            sms.Conversation_Header__c = chId;
                            if(!String.isBlank(sms.Message__c)){
                                if(!chIdtoRetrieve.contains(chId)){
                                    Conversation_Header__c chl = [SELECT Id, MessagePreview__c FROM Conversation_Header__c WHERE Id =:chId];
                                    String inboundMessage = String.valueOf(sms.Message__c);
                                    if(!String.isBlank(inboundMessage) && inboundMessage.length()>=255 && sms.Source__c =='LiveText'){
                                        chl.MessagePreview__c = inboundMessage.substring(0,255);
                                    }
                                    if(!String.isBlank(inboundMessage) && inboundMessage.length()<255 && sms.Source__c =='LiveText'){
                                        chl.MessagePreview__c = inboundMessage;
                                    }
                                    updateMessagePreview.add(chl);
                                    chIdtoRetrieve.add(chId);
                                }
                            }
                        }else if(sms.Source__c == Constant.live_text) { 
                            // Only for incoming SMS Text we need to create new Conversation header
                            // If Conversation header is not found then create the new conversation header
                            String phNoCombination = getKey(sms);
                            //check if we reopened conversation
                            if(updateChHeaderStatusNewMap.get(phNoCombination) == null){
                                List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                                if(smsList == null || smsList.isEmpty()){
                                    smsList = new List<SMS_Text__c>();
                                    smsList.add(sms);
                                }else{
                                    smsList.add(sms);
                                }
                                smsWithoutConvHeaderMap.put(phNoCombination, smsList);
                            }
                        }
                    }

                    if(!updateMessagePreview.isEmpty()){
                        AccessController.upsertAsSystem(updateMessagePreview);
                    }

                    if(!smsWithoutConvHeaderMap.isEmpty()){
                        //get routing info only if needed
                        routingInfo = new SMSTextListRoutingInfo(newSmsTexList);
                        for(String phNoCombination : smsWithoutConvHeaderMap.keySet()){
                            List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                            //Lt-1274
                            if(smsList != null && !smsList.isEmpty() && updateChHeaderStatusNewMap.get(phNoCombination) == null){
                                //create new conversation if it's ok to route
                                Boolean okToRoute =  routingInfo.isOkToRoute(smsList.get(0));
                                if(okToRoute){
                                    Conversation_Header__c convObj = new Conversation_Header__c();
                                    convObj.Originating_Number__c = smsList.get(0).Originating_Number__c;
                                    convObj.Support_Number__c = smsList.get(0).Support_Number__c;
                                    convObj.Status__c = Constant.stage_new;
                                    convObj.ConversationType__c = Constant.ConversationType.Inbound.name();
                                    convObj.SessionReopenedTime__c = System.now();
                                    if(!String.isBlank(smsList.get(0).Message__c)){
                                        if(String.valueOf(smsList.get(0).Message__c).length() >= 255){
                                            convObj.MessagePreview__c = String.valueOf(smsList.get(0).Message__c).substring(0,255);
                                        }else{
                                            convObj.MessagePreview__c = String.valueOf(smsList.get(0).Message__c);
                                        }
                                    }
                                    newConversationHeaderList.add(convObj);
                                }
                            }
                        }
                    }
                }
              
                if(!newConversationHeaderList.isEmpty()){
                    AccessController.insertAsSystem(newConversationHeaderList);
                    for(Conversation_Header__c ch : newConversationHeaderList){
                        if(ch != null){
                            String phNoCombination = getKey(ch);
                            List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                            for(SMS_Text__c sms : smsList){
                                sms.Conversation_Header__c = ch.Id;
                            }
                        }
                    }
                }
             
                if(!updateStatusToNewList.isEmpty()){
                    AccessController.updateAsSystem(updateStatusToNewList);
                    for(Conversation_Header__c ch : updateStatusToNewList){
                        if(ch != null){
                            String phNoCombination = getKey(ch);
                            SMS_Text__c s = smsTextMap.get(phNoCombination);
                            s.Conversation_Header__c = ch.Id;
                        }
                    }
                }
            }
        } catch (exception e) {
            Util.insertException(Constant.sms_text_obj + Constant.before_insert, Constant.priority_high, e.getMessage() + ', Line number: ' + e.getLineNumber());
        }
    }
    
    private void handleITR(List<SMS_Text__c> newSmsTexList, Map<Id,Boolean> SMSTextBusinessHourValidationMap) {
        try {
            SMSTextListRoutingInfo routingInfo = new SMSTextListRoutingInfo(newSmsTexList);             
            Map<String, List<SMS_Text__c>> smsWithoutConvHeaderMap = new Map<String, List<SMS_Text__c>>();
            Set<String> orginatingPhNoList = new Set<String>();
            Set<String> orginatingNoList = new Set<String>();
            Set<String> supportPhNoList = new Set<String>();
            Set<Id> supportPhNoIdList = new Set<Id>();
            for (SMS_Text__c sms: newSmsTexList) {
                // Only for incoming SMS Text or ITR with no conversation header 
                if((sms.Source__c == Constant.live_text || sms.Source__c == Constant.ITR || sms.Source__c == Constant.permission_marketing) && sms.Conversation_Header__c == null) {
                    String phNoCombination = getKey(sms);
                    List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                    if(smsList == null || smsList.isEmpty()){
                        smsList = new List<SMS_Text__c>();
                        smsList.add(sms);
                    }else{
                        smsList.add(sms);
                    }
                    smsWithoutConvHeaderMap.put(phNoCombination, smsList);
                }
              
            }
            Map<Id,String> ltnPhoneMap = new Map<Id,String>();
            for(LiveText_Number__c ltn : [SELECT Id, Number__c FROM LiveText_Number__c]){
                ltnPhoneMap.put(ltn.Id,ltn.Number__c);
            }
            for(String phNoCombination : smsWithoutConvHeaderMap.keySet()) {
                List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                if(smsList != null && !smsList.isEmpty()){
                    for(SMS_Text__c sms : smsList) {
                        if(!orginatingPhNoList.contains(sms.Originating_Number__c)){
                            orginatingPhNoList.add(Util.NormalizePhoneNumber(sms.Originating_Number__c));
                            orginatingNoList.add(sms.Originating_Number__c);
                        }
                        
                        String supportNo = ltnPhoneMap.get(sms.Support_Number__c);
                        if(!String.isBlank(supportNo) && !supportPhNoList.contains(supportNo)){
                            supportPhNoList.add(supportNo);
                            supportPhNoIdList.add(sms.Support_Number__c);
                        }
                    }
                }
            }

            Map<String,Id> recentCampaignPhoneMap = new Map<String,Id>();
            List<Recent_Campaign_Send_Member__c> recentCampaignList = new List<Recent_Campaign_Send_Member__c>();
            for(Recent_Campaign_Send_Member__c rcsm :[SELECT Id,CampaignSendMember__c,CampaignSendMember__r.FromNumber__c,CampaignSendMember__r.Phone__c
                                                        FROM Recent_Campaign_Send_Member__c 
                                                        WHERE CampaignSendMember__r.FromNumber__c IN: supportPhNoList 
                                                            AND CampaignSendMember__r.Phone__c IN: orginatingPhNoList
                                                        LIMIT 50000]){
                recentCampaignPhoneMap.put(rcsm.CampaignSendMember__r.FromNumber__c +'->'+ rcsm.CampaignSendMember__r.Phone__c,rcsm.CampaignSendMember__c);
            }

            Map<Id, Set<Id>> ltNumberToAvaliableAgentsMap = Util.getAvailableAgentsMap();
            Map<String,Decimal> ltnOptinStatusMap = Util.getOptInStatus(supportPhNoIdList, orginatingNoList);
            Map<String,ITR_Message__c> existingMsgsMap = new Map<String,ITR_Message__c>();
            for(ITR_Message__c msg : [SELECT Id, HTML_Transcript__c, Mo_Message_Counter__c, Available_Agents__c,LiveText_Number__c,Originating_Number__c,Message__c
                                        FROM ITR_Message__c 
                                        WHERE Originating_Number__c IN: orginatingNoList 
                                            AND  LiveText_Number__c IN: supportPhNoIdList
                                        ORDER BY LastModifiedDate DESC NULLS FIRST LIMIT 50000]){
                existingMsgsMap.put(msg.LiveText_Number__c + '->' + msg.Originating_Number__c,msg);
            }
            for(String phNoCombination : smsWithoutConvHeaderMap.keySet()){
                List<SMS_Text__c> smsList = smsWithoutConvHeaderMap.get(phNoCombination);
                if(smsList != null && !smsList.isEmpty()){
                    handleITRMessagesForSingleConversation(routingInfo, smsList, SMSTextBusinessHourValidationMap,recentCampaignPhoneMap,ltnPhoneMap,ltNumberToAvaliableAgentsMap,ltnOptinStatusMap,existingMsgsMap);
                }
            } 
        } catch (exception e) {
            Util.insertException(Constant.sms_text_obj + Constant.after_insert, Constant.priority_high, e.getMessage());
        }
    }
    
    private void handleITRMessagesForSingleConversation(SMSTextListRoutingInfo routingInfo, List<SMS_Text__c> smsList, Map <Id, Boolean> SMSTextBusinessHourValidationMap,Map<String,ID> recentCampaignPhoneMap,Map<Id,String> ltnPhoneMap,Map<Id, Set<Id>> ltNumberAvaliableAgentsMap,Map<String,Decimal>ltnOptinStatusMap,Map<String,ITR_Message__c> existingMsgsMap){

        if(smsList != null && smsList.size() > 0){
            Map<Id, Set<Id>> ltNumberToAvaliableAgentsMap = new Map<Id, Set<Id>>();
            ltNumberToAvaliableAgentsMap = ltNumberAvaliableAgentsMap;
            SMS_Text__c firstMsg = smsList[0];
            Decimal optInStatus;
            String num = firstMsg.Support_Number__c + '->' + firstMsg.Originating_Number__c;
            if(ltnOptinStatusMap!=null){
                optInStatus = ltnOptinStatusMap.get(firstMsg.Support_Number__c + '->' + firstMsg.Originating_Number__c);
            }
            String msgOptInStatus = null;
            if(optInStatus != null){
                 msgOptInStatus = optInStatus == 1 ? '1' : '0';
            }

            List<ITR_Message__c> existingMsgs = new List<ITR_Message__c>();
            ITR_Message__c msg = new ITR_Message__c();
            String transcript = '';

            if(existingMsgsMap !=null && existingMsgsMap.containsKey(num)) {
                msg = existingMsgsMap.get(num);
                transcript = msg.HTML_Transcript__c;
            }else{
                msg = null;
                transcript = '';
            }
            transcript = Util.createITRTranscript(transcript, smsList);
            PhoneNumberRelatedObjects relatedObjects = null;
            try{
                relatedObjects = new PhoneNumberRelatedObjects(firstMsg.Support_Number__c, firstMsg.Originating_Number__c);
            }
            catch(Exception ex){
                Util.insertException('handleITRMessagesForSingleConversation', constant.priority_high, ex.getMessage());
            }
            for(SMS_Text__c sms : smsList){
                Boolean isWithinBusinessHours = SMSTextBusinessHourValidationMap.get(sms.Id);
                if(msg == null && sms.Source__c == Constant.live_text){
                    msg = new ITR_Message__c();
                    msg.Originating_Number__c = firstMsg.Originating_Number__c;
                    msg.LiveText_Number__c = firstMsg.Support_Number__c;
                    msg.Is_Within_Business_Hours__c = isWithinBusinessHours;
                    msg.HTML_Transcript__c = transcript;
                    msg.Text_Transcript__c = Util.convertTranscriptToPlainText(transcript);
                    if(msg.Mo_Message_Counter__c == null){
                        msg.Mo_Message_Counter__c = 0;
                    }
                    msg.Mo_Message_Counter__c = msg.Mo_Message_Counter__c+1;
                    List<Id> temp = new List<Id>();
                    if(ltNumberToAvaliableAgentsMap.containsKey((Id) firstMsg.Support_Number__c)){
                        temp.addAll(ltNumberToAvaliableAgentsMap.get((Id) firstMsg.Support_Number__c));
                    }
                    msg.Available_Agents__c = temp.size();
                   
                    AccessController.insertAsSystem(new List<ITR_Message__c>{msg});              
                }
                
                if(msg != null){
                    if(sms.Source__c == Constant.live_text){
                    	msg.Campaign_Send_Member__c = null;
                    	if(recentCampaignPhoneMap != null) {
                        	if(firstMsg.Originating_Number__c != null) {
                            	String pnoKey =ltnPhoneMap.get(firstMsg.Support_Number__c) +'->'+ firstMsg.Originating_Number__c; 
                            	if(recentCampaignPhoneMap.containsKey(pnoKey)) {
                                	msg.Campaign_Send_Member__c = recentCampaignPhoneMap.get(pnoKey);
                            	}
                        	}
                    	}
                    
                        msg.Message__c = sms.Message__c;
                        msg.Opt_In_Status__c = msgOptInStatus;
                        msg.Is_Within_Business_Hours__c = isWithinBusinessHours;
                        if(relatedObjects != null){
                            try{
                                if(relatedObjects.HasItems){
                                    Map<String, String> relationshipObjectApiNameToFieldNameMap = new Map<String, String>();
                                    Map<String, Schema.SObjectField> fieldMap = msg.getSObjectType().getDescribe().fields.getMap();
                                    for(String field : fieldMap.keySet()){
                                        if(fieldMap.get(field).getDescribe().getRelationshipName() != null && fieldMap.get(field).getDescribe().isCustom()){
                                            relationshipObjectApiNameToFieldNameMap.put(fieldMap.get(field).getDescribe().getReferenceTo().get(0).getDescribe().getName(), field);
                                        }
                                    }
                                    for(String relationshipName : Util.getAllRelationshipObjects(msg.getSObjectType().getDescribe().getName())){
                                        msg.put(relationshipObjectApiNameToFieldNameMap.get(relationshipName), PhoneNumberRelatedObjects.getMRMItem(relatedObjects.CustomObjects, fieldMap.get(relationshipObjectApiNameToFieldNameMap.get(relationshipName)).getDescribe().getReferenceTo().get(0).getDescribe().getName()));
                                    }
                                }
                            }
                            catch(Exception ex){
                                Util.insertException('handleITRMessagesForSingleConversation', constant.priority_high, ex.getMessage());
                            } 
                        }
                    }
                    msg.HTML_Transcript__c = transcript;
                    msg.Text_Transcript__c = Util.convertTranscriptToPlainText(transcript);
                    if(msg.Mo_Message_Counter__c == null){
                        msg.Mo_Message_Counter__c = 0;
                    }
                    msg.Mo_Message_Counter__c = msg.Mo_Message_Counter__c+1;
                    List<Id> temp = new List<Id>();
                    if(ltNumberToAvaliableAgentsMap.containsKey((Id) firstMsg.Support_Number__c)){
                        temp.addAll(ltNumberToAvaliableAgentsMap.get((Id) firstMsg.Support_Number__c));
                    }
                    msg.Available_Agents__c = temp.size();
                    AccessController.updateAsSystem(new List<ITR_Message__c>{msg});
                } 
            }
        }
    }         
        
    /**
     * @description
     * @param
     * @return void
     */
    private void afterInsertUpdate(List<SMS_Text__c> newRecords, Map<Id, SMS_Text__c> newSmsTextMap, Map<Id, SMS_Text__c> oldSmsTextMap) {
        try {
            Map<Id, SMS_Text__c> referenceSmsTextMap = new Map<Id, SMS_Text__c> ();
            referenceSmsTextMap = newSmsTextMap.clone();
            Map<Id, SMS_Text__c> filteredSmsTextMap = new Map<Id, SMS_Text__c> ();
            Map<Id, Boolean> SMSTextBusinessHourValidationMap = Util.isWithinBusinessHours(newSmsTextMap.values());
            Map<Id, Id> smsConversationHeaderMap = new Map<Id, Id>();
            List<Id> conversationHeaderIdList = new List<Id>();
            
            handleITR(newRecords, SMSTextBusinessHourValidationMap);
            
            // identify if smstext record's source is LiveText.
            // because we need to send them out of business hours message, if message is sent out of business hours.
            for (SMS_Text__c sms : newSmsTextMap.values()){
                if (sms.Source__c == Constant.live_text){
                    filteredSmsTextMap.put(sms.Id, sms);
                    smsConversationHeaderMap.put(sms.Id, sms.Conversation_Header__c);
                }
            }
    
            // We don't want to create conversation header records out of SMSText records if 
            // SMSText records are created outside of business hours. so remove those Id's from original
            // map been passed (newSmsTextMap)
            Map<Id, SMS_Text__c> offlineConversationHeaderMap = new Map<Id, SMS_Text__c>();
            
            for (Id smsTextId : SMSTextBusinessHourValidationMap.KeySet()) {
                // check if conversation header is in offline hours
                if (!SMSTextBusinessHourValidationMap.get(smsTextId)) {
                    offlineConversationHeaderMap.put(smsTextId,referenceSmsTextMap.get(smsTextId));
                    referenceSmsTextMap.remove(smsTextId);
                    conversationHeaderIdList.add(smsConversationHeaderMap.get(smsTextId));
                }
            }
            
            if (!offlineConversationHeaderMap.isEmpty()) {
               // process SMS Texts that came in outside of business hours
               // update conversation header with status of off_line
                List<Conversation_Header__c> chList = [SELECT Id, Status__c, Support_Number__r.Notify_Users_During_Off_Hours__c FROM Conversation_Header__c WHERE Id IN :conversationHeaderIdList];
                if (chList != null && !chList.isEmpty()) {
                    for(Conversation_Header__c ch: chList) {
                        //LT-1166 for itr disabled
                        if(ch.Support_Number__r.Notify_Users_During_Off_Hours__c || ch.Status__c == Constant.stage_active){
                            if(!(ch.Status__c == Constant.stage_ended) && !(ch.Status__c == Constant.stage_active)){
                                ch.Status__c = Constant.stage_new;
                                ch.SessionReopenedTime__c = system.now();

                            }
                        }else{
                            ch.Status__c = Constant.stage_offline;
                        }
                    }
                    AccessController.updateAsUser(chList);
                }
            }
        } catch (exception e) {
            Util.insertException(Constant.conversation_header_obj + Constant.after_insert, Constant.priority_high, e.getMessage());
        }
    }
}