LiveText-LiveText3.14/src/objects/ConfigurationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores the HeyWire OAuth connection detail.</description>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <inlineHelpText>Url of the connected org</inlineHelpText>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>oAuth_URL__c</fullName>
        <description>URL for oAuth</description>
        <inlineHelpText>URL for starting the oAuth flow</inlineHelpText>
        <label>oAuth URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Configuration Settings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>ElapsedTime__c</fullName>
        <description>Calculates elapsed time since record creation.</description>
        <formula>floor((NOW() -  SessionReopenedTime__c)* 1440*60)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ElapsedTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number_To_Display__c</fullName>
        <description>Formatted Originating Number for international numbers using google js lib</description>
        <label>Formatted Originating Number To Display</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number__c</fullName>
        <formula>IF((LEN(Formatted_Originating_Number_To_Display__c) = 0 || Formatted_Originating_Number_To_Display__c = null),  Originating_Number__c, Formatted_Originating_Number_To_Display__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Originating Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <formula>Support_Number__r.Formatted_Support_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LiveText Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Number from which the SMS has been generated.</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support number that is LiveText enabled.</description>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>CreateEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateEvent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateTask__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CreateTask</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISOCountryCode__c</fullName>
        <defaultValue>&quot;US&quot;</defaultValue>
        <description>ISO 3166-1 alpha-2 country code</description>
        <label>ISO Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>International_Live_Text_Number__c</fullName>
        <description>International Live Text Number</description>
        <label>International Live Text Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Custom_Objects_Tabs__c</fullName>
        <description>Setting for custom objects feature</description>
        <label>New_Custom_Objects_Tabs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Show_New_Account_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Account tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Case_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Case tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Contact_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Contact tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Lead_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Lead tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Opportunity_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Opportunity tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveTextGlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Global Settings.</description>
    <fields>
        <fullName>Active_Status_Purge_Hours__c</fullName>
        <description>specify hours to change conversation header&apos;s Active status to Ended.</description>
        <label>Active Status Purge Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GlobalTriggerExecutionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GlobalTriggerExecutionEnabled if checked will enable/ disable all triggers in Organisation.</description>
        <label>GlobalTriggerExecutionEnabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Status_Purge_Hours__c</fullName>
        <label>New Status Purge Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offline_Status_Purge_Hours__c</fullName>
        <label>Offline Status Purge Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LiveTextGlobalSettings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number__c</fullName>
        <formula>IF(LEFT(Originating_Number__c,2)==&apos;+1&apos;, LEFT(Originating_Number__c, 2)+&apos; (&apos;+MID(Originating_Number__c,3,3)+&apos;) &apos;+MID(Originating_Number__c,6,3)+&apos;-&apos;+RIGHT(Originating_Number__c,4), &apos;+1&apos;+&apos; (&apos;+LEFT(Originating_Number__c,3)+&apos;) &apos;+MID(Originating_Number__c,4,3)+&apos;-&apos;+RIGHT(Originating_Number__c,4))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Originating Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LiveText</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/PostInstallHandler.cls
/**
 * @author        Santosh Gudge (santosh@comitydesigns.com)
 * @company       ComityDesigns
 * @date          07/18/2014
 * @description   PostInstall script, runs when package is being installed.
 */
global class PostInstallHandler implements InstallHandler {
    
    global void onInstall(InstallContext context) {
        String result = 'start';
        system.debug('context'+context);
        try{  
            if (context.previousVersion() == null) {
                createConfigurationSettings();
                createGlobalSettings();
                List<PushTopic> pushTopicList = new List<PushTopic>();
                pushTopicList.add(createConversationHeaderPushTopic());
                pushTopicList.add(createSMSTextPushTopic());
                insert pushTopicList; // DO NOT INCLUDE ACCESS CONTROLLER HERE AS IT WILL FAIL.
            } 
            if(context.previousVersion() != null && context.previousVersion().compareTo(new Version(3,5)) < 0){
                setPhoneNumbersActivities();
            }
            
            if(context.previousVersion() != null && context.previousVersion().compareTo(new Version(3,8)) < 0){
                migrateNewTabSettings();
            }
            
            normalizeLiveTextNumbers();
            setPhoneNumbersISOCountryCode();
            setInternationalPhoneNumbers();
            createSemaphores();

        }catch(Exception ex) {
            Messaging.SingleEmailMessage emailTobeSent = new Messaging.SingleEmailMessage();
            list<String> listEmailMembers = new list<String>();
            //remove below code after testing
            listEmailMembers.add(Label.TXT_AdminEmail);
            emailTobeSent.setToAddresses(listEmailMembers);
            emailTobeSent.setSubject('Post install exception');
            emailTobeSent.setHtmlBody('Message : ' + ex.getMessage() + 'Line no : ' + ex.getLineNumber() + ' getStackTraceString ' + ex.getStackTraceString() + '' + ex.getCause());
            Messaging.SendEmailResult [] r1 = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailTobeSent});
        }
    }

    private void createConfigurationSettings(){    
        ConfigurationSettings__c confSettings = new ConfigurationSettings__c(
            Name = Constant.HEYWIRE_CONFIG,
            EndPoint_URL__c = Constant.HEYWIRE_PRODUCTION_URL,
            oAuth_URL__c = Constant.HEYWIRE_PRODUCTION_OAUTH_URL);
        insert confSettings;
    }
    
    private void createGlobalSettings(){
        LiveTextGlobalSettings__c ltgs = LiveTextGlobalSettings__c.getInstance(UserInfo.getOrganizationId());
        if (ltgs.SetupOwnerId == null) {
            insert new LiveTextGlobalSettings__c(GlobalTriggerExecutionEnabled__c = true,
                Active_Status_Purge_Hours__c = 48,
                New_Status_Purge_Hours__c = 1,
                Offline_Status_Purge_Hours__c =1,
                SetupOwnerId = UserInfo.getOrganizationId());
        }
    }
    
    private void createSemaphores(){
        Semaphore.Create(constant.SEMAPHORE_SMS_TEXT_TRIGGER_HANDLER);
        Semaphore.Create(constant.SEMAPHORE_INBOUND_PHONE_FORMAT);
    }
    
    private void migrateNewTabSettings(){
    	
    	List<LiveText_Number__c> ltnObjects = Database.query('SELECT Id, Show_New_Account_Tab__c, Show_New_Contact_Tab__c, Show_New_Lead_Tab__c, Show_New_Case_Tab__c,Show_New_Opportunity_Tab__c, New_Custom_Objects_Tabs__c FROM LiveText_Number__c Where Show_New_Account_Tab__c=true OR Show_New_Contact_Tab__c=true OR Show_New_Lead_Tab__c=true OR Show_New_Case_Tab__c=true OR Show_New_Opportunity_Tab__c=true');
 
 		for(LiveText_Number__c ltnObject : ltnObjects){    	
	   		if(ltnObject.New_Custom_Objects_Tabs__c == null) ltnObject.New_Custom_Objects_Tabs__c = '';
	    	
	    	if(ltnObject.Show_New_Account_Tab__c == true){
	    		ltnObject.New_Custom_Objects_Tabs__c += Util.GLOBAL_DESCRIBE.get(Constant.ACCOUNT_OBJECT).getDescribe().getName() + ';';
	    	}
	    	
	    	if(ltnObject.Show_New_Contact_Tab__c == true){
	    		ltnObject.New_Custom_Objects_Tabs__c += Util.GLOBAL_DESCRIBE.get(Constant.CONTACT_OBJECT).getDescribe().getName() + ';';
	    	}
	    	
	    	if(ltnObject.Show_New_Lead_Tab__c == true){
	    		ltnObject.New_Custom_Objects_Tabs__c += Util.GLOBAL_DESCRIBE.get(Constant.LEAD_OBJECT).getDescribe().getName() + ';';
	    	}
	    	
	    	if(ltnObject.Show_New_Case_Tab__c == true){
	    		ltnObject.New_Custom_Objects_Tabs__c += Util.GLOBAL_DESCRIBE.get(Constant.CASE_OBJECT).getDescribe().getName() + ';';
	    	}   	 	
	    	
	    	if(ltnObject.Show_New_Opportunity_Tab__c == true){
	    		ltnObject.New_Custom_Objects_Tabs__c += Util.GLOBAL_DESCRIBE.get(Constant.OPPORTUNITY_OBJECT).getDescribe().getName() + ';';
	    	}
		}
	 	
	 	if(ltnObjects.size() > 0){
	 		update ltnObjects;
	 	}      
    }
        
    private PushTopic createConversationHeaderPushTopic(){
        String streamingObjectName = Conversation_Header__c.SObjectType.getDescribe().getName();
        String idField = Conversation_Header__c.Id.getDescribe().getName();
        String supportNumberField = Conversation_Header__c.Support_Number__c.getDescribe().getName();
        String originatingNumberField = Conversation_Header__c.Originating_Number__c.getDescribe().getName();
        String formattedOriginatingNumberField = Conversation_Header__c.Formatted_Originating_Number__c.getDescribe().getName();
        String stageField = Conversation_Header__c.Status__c.getDescribe().getName();
        String liveTextNumberField = Conversation_Header__c.LiveText_Number__c.getDescribe().getName();
        String elapsedTimeField = Conversation_Header__c.ElapsedTime__c.getDescribe().getName();
        String formattedOriginatingNumberToDisplay = Conversation_Header__c.Formatted_Originating_Number_To_Display__c.getDescribe().getName();
        String query = 'Select';
        query += ' ' + idField + ', ';
        query += supportNumberField + ', ';
        query += originatingNumberField + ', ';
        query += formattedOriginatingNumberField + ', ';
        query += formattedOriginatingNumberToDisplay + ',';
        query += liveTextNumberField + ', ';
        query += elapsedTimeField + ', ';
        query += stageField + ' ';
        query += 'from ' + streamingObjectName;
        system.debug('query::' + query);
        PushTopic pushTopic = new PushTopic();
        String pushTopicName = Test.isRunningTest()?Constant.conversation_header_push_topic_Test:Constant.conversation_header_push_topic;
        pushTopic.Name = pushTopicName;
        pushTopic.isActive = true;
        pushTopic.Query = query;
        pushTopic.ApiVersion = 31.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = true;
        pushTopic.NotifyForOperationUndelete = true;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced';
        return pushTopic;
    }
    
    /**
     * @description: Create a PushTopic,for any new records inserted to SMS text object having source as livetext.
     * @param: null.
     * @return null.
     */
    private PushTopic createSMSTextPushTopic() {
        String streamingObjectName = SMS_Text__c.SObjectType.getDescribe().getName();
        String idField = SMS_Text__c.Id.getDescribe().getName();
        String supportNumberField = SMS_Text__c.Support_Number__c.getDescribe().getName();
        String originatingNumberField = SMS_Text__c.Originating_Number__c.getDescribe().getName();
        String formattedOriginatingNumberField = SMS_Text__c.Formatted_Originating_Number__c.getDescribe().getName();
        String SourceField = SMS_Text__c.Source__c.getDescribe().getName();
        String ConversationHeaderField = SMS_Text__c.Conversation_Header__c.getDescribe().getName();
        String smsTextOrigine = 'LiveText';
        String query = 'Select';
        query += ' ' + idField + ', ';
        query += supportNumberField + ', ';
        query += originatingNumberField + ', ';
        query += formattedOriginatingNumberField + ', ';
        query += SourceField + ', ';
       // query += ConversationHeaderField + ', ';
       // query += MessageField + ' ';
        query += ConversationHeaderField + ' ';
        query += 'from ' + streamingObjectName;
        query += ' where  ' + SourceField + '=' + '\'' + smsTextOrigine + '\'';
        PushTopic pushTopic = new PushTopic();
        String pushTopicName = Test.isRunningTest()?Constant.sms_text_push_topic_Test:Constant.sms_text_push_topic;
        pushTopic.Name = pushTopicName;
        pushTopic.Query = query;
        pushTopic.isActive = true;
        pushTopic.ApiVersion = 31.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = true;
        pushTopic.NotifyForOperationUndelete = true;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced'; 
        return pushTopic;
    }

    private void setPhoneNumbersActivities(){
        List<LiveText_Number__c> updateNumbers = [SELECT Id, CreateEvent__c, CreateTask__c FROM LiveText_Number__c];
        for(LiveText_Number__c n : updateNumbers){
            if(!n.CreateEvent__c && !n.CreateTask__c){
                n.CreateEvent__c = false;
                n.CreateTask__c = true;
            }
        }
        update updateNumbers;
    }
    
    private void normalizeLiveTextNumbers(){
         List<LiveText_Number__c> updateNumbers = [SELECT Id, Number__c FROM LiveText_Number__c WHERE not Number__c like '+%'];
         for(LiveText_Number__c n : updateNumbers){
            n.Number__c = '+' + n.Number__c;
        }
        update updateNumbers;
    }

    private void setPhoneNumbersISOCountryCode(){
        List<LiveText_Number__c> updateNumbers = [SELECT Id, ISOCountryCode__c FROM LiveText_Number__c WHERE ISOCountryCode__c = null];
        for(LiveText_Number__c n : updateNumbers){
            n.ISOCountryCode__c = 'US';
        }
        update updateNumbers;
    }

    private void setInternationalPhoneNumbers() {
        List<LiveText_Number__c> updateNumbers = [SELECT Id, International_Live_Text_Number__c, Number__c FROM LiveText_Number__c WHERE International_Live_Text_Number__c = null];
        for(LiveText_Number__c n : updateNumbers){
            n.International_Live_Text_Number__c = n.Number__c;
        }
        update updateNumbers;
    }

}