LiveText-LiveText3.14/src/objects/ConfigurationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores the HeyWire OAuth connection detail.</description>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <inlineHelpText>Url of the connected org</inlineHelpText>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <label>Configuration Settings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support number that is LiveText enabled.</description>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Exception__c.object
<CustomObject>
    <description>Exception</description>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>Object Id.</description>
        <label>ObjectId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>LiveText Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/Inbound_Connection_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Connection Status from LiveText to Salesforce</description>
    <label>Inbound Connection Status</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/CalloutTest.cls
@isTest
private class CalloutTest {    
    static Inbound_Connection_Status__c connStatus;
    static ConfigurationSettings__c confSettings;
    static Conversation_Header__c conversationHeader;
    static SMS_Text__c smsTextObject;
    static SObject ltnObject;    
    static {
        confSettings = UnitTestObjectBuilder.CreateConfigurationSettings();
        connStatus = UnitTestObjectBuilder.CreateConnectionStatus();
    }

    /*
     *  Create Livetext number
     * Creating conversation header
     * Creating SMS Text Object
    */
    static void initTestData() {
        ltnObject = UnitTestObjectBuilder.createLiveTextNumber();
        insert ltnObject;
        System.assertNotEquals(ltnObject.Id, null);
        conversationHeader = CommonTestHelper.CreateConversationHeader(Constant.OriginatingNumber,ltnObject.Id);
        insert conversationHeader;
        System.assertNotEquals(conversationHeader.Id, null);
        smsTextObject = UnitTestObjectBuilder.CreateSMSTextRecord(ltnObject, conversationHeader.Id);
        insert smsTextObject;
        System.assertNotEquals(smsTextObject.Id, null);
    }
    
    static testMethod void Test_SendSMS_Positive() {
        HttpResponse response;
        initTestData();
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + String.format(Constant.HEYWIRE_API_SEND_SMS, 
                                        new String[]{(String)ltnObject.get('Number__c')});
        System.assertNotEquals(endPoint, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(204, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        Boolean smsSent = Callout.sendSMS(smsTextObject, 'Hi how are you?');
        system.assertEquals(smsSent, true);
        Test.stopTest();
    }
    
    static testMethod void Test_SendSMS_Negative() {
        initTestData();
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + String.format(Constant.HEYWIRE_API_SEND_SMS, 
                                        new String[]{(String)smsTextObject.get('Support_Number__c')});
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(500, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Test.setMock(HttpCalloutMock.class, fakePhNoExistResp);
        Boolean smsSent = Callout.sendSMS(smsTextObject, 'Hi how are you?');
        System.assertNotEquals(smsSent, true);
        Test.stopTest();
    }
    
    static testMethod void Test_addResponseError() {
        initTestData();
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + String.format(Constant.HEYWIRE_API_SEND_SMS, 
                                        new String[]{(String)smsTextObject.get('Support_Number__c')});
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(500, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Test.setMock(HttpCalloutMock.class, fakePhNoExistResp);
        Boolean smsSent = Callout.sendSMS(smsTextObject, 'Hi how are you?');
        System.assertNotEquals(smsSent, true);
        Test.stopTest();
    }
    
    static testMethod void Test_doesPhoneNoExistInternal() {
        initTestData();
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(401, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Test.setMock(HttpCalloutMock.class, fakePhNoExistResp);
        HttpResponse response = Callout.doesPhoneNoExistInternal(phoneNumber);
        System.assertNotEquals(response, null);
        Test.stopTest();
    }
    
    static testMethod void Test_DoesPhNoExist_Positive() {
        HttpResponse response;
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + Constant.HEYWIRE_API_GET_PHONE_NUMBER + phoneNumber;
        System.assertNotEquals(endPoint, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(200, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        System.assertNotEquals(httpRequestCalloutMock, null);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        
        Boolean phExist = Callout.doesPhoneNoExist(phoneNumber);
        system.assert(phExist);
        Test.stopTest();
    }
    
    static testMethod void Test_CanDeletePhoneNo_Positive() {
        HttpResponse response;
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + Constant.HEYWIRE_API_GET_PHONE_NUMBER + phoneNumber;
        System.assertNotEquals(endPoint, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(404, 'OK', null, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        System.assertNotEquals(httpRequestCalloutMock, null);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        
        Boolean canDelete = Callout.canDeletePhoneNo(phoneNumber);
        system.assert(canDelete);
        Test.stopTest();
    }
    
    static testMethod void Test_CanDeletePhoneNo_200Response() {
        HttpResponse response;
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + Constant.HEYWIRE_API_GET_PHONE_NUMBER + phoneNumber;
        System.assertNotEquals(endPoint, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(200, 'OK', null, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        System.assertNotEquals(httpRequestCalloutMock, null);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        
        Boolean canDelete = Callout.canDeletePhoneNo(phoneNumber);
        system.assertEquals(canDelete, false);
        System.AssertEquals(ApexPages.getMessages()[0].getSeverity(), ApexPages.Severity.ERROR);
        System.AssertEquals(ApexPages.getMessages()[0].getSummary(), system.label.CannotDeleteSupportNoMsg);
        Test.stopTest();
    }
    
    static testMethod void Test_CanDeletePhoneNo_Negative() {
        HttpResponse response;
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + Constant.HEYWIRE_API_GET_PHONE_NUMBER + phoneNumber;
        System.assertNotEquals(endPoint, null);
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(401, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        
        Boolean canDelete = Callout.canDeletePhoneNo(phoneNumber);
        system.assertEquals(canDelete, false);
        System.AssertEquals(ApexPages.getMessages()[0].getSeverity(), ApexPages.Severity.ERROR);
        Test.stopTest();
    }
    
    static testMethod void Test_SendSMSViaTrigger() {
        HttpResponse response;
        initTestData();
        Test.startTest();
        String phoneNumber = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        System.assertNotEquals(phoneNumber, null);
        String endPoint = confSettings.EndPoint_URL__c + String.format(Constant.HEYWIRE_API_SEND_SMS, 
                                        new String[]{(String)ltnObject.get('Number__c')});
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(500, 'OK', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        System.assertNotEquals(httpRequestCalloutMock, null);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        Callout.sendSMSViaTrigger(new List<Id>{smsTextObject.Id});
        Test.stopTest();
        List<Exception__c> ex = [Select Id From Exception__c Where ObjectId__c=:smsTextObject.Id];
        System.assert(!ex.isEmpty());
    }
    
    static testMethod void Test_ValidateAccCredentials_Positive() {
        HttpResponse response;
        //Prudhvi: Did not use the initTestData as the conversations are not required for the account validation.
        ltnObject = UnitTestObjectBuilder.createLiveTextNumber();
        insert ltnObject;
        
        Test.startTest();
        String endPoint = confSettings.EndPoint_URL__c + String.format(Constant.HEYWIRE_API_LOOKUP_ACCOUNT, 
                                        new String[]{(String)ltnObject.get('Number__c')});
        HTTPRequestMockTest fakePhNoExistResp = new HTTPRequestMockTest(401, 'Unauthorized', null, null);
        System.assertNotEquals(fakePhNoExistResp, null);
        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put(endPoint, fakePhNoExistResp);
        HttpCalloutMock httpRequestCalloutMock = new HTTPRequestMockTest(endpoint2TestResp);
        System.assertNotEquals(httpRequestCalloutMock, null);
        Test.setMock(HttpCalloutMock.class, httpRequestCalloutMock);
        Boolean isValid = Callout.validateAccCredentials(confSettings, (String)ltnObject.get('Number__c'));
        system.assertEquals(isValid, false);
        system.assertEquals(false, isValid);
        Test.stopTest();
    }
}