LiveText-LiveText3.14/src/objects/ConfigurationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores the HeyWire OAuth connection detail.</description>
    <label>Configuration Settings</label>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>CreateEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateEvent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateTask__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CreateTask</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Custom_Objects_Tabs__c</fullName>
        <description>Setting for custom objects feature</description>
        <label>New_Custom_Objects_Tabs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Show_New_Account_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Account tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Case_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Case tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Contact_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Contact tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Lead_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Lead tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_New_Opportunity_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether or not to show the New Opportunity tab when a text session is started for this phone number.</inlineHelpText>
        <label>Show New Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveTextGlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Global Settings.</description>
    <fields>
        <fullName>GlobalTriggerExecutionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GlobalTriggerExecutionEnabled if checked will enable/ disable all triggers in Organisation.</description>
        <label>GlobalTriggerExecutionEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>LiveTextGlobalSettings</label>
</CustomObject>

LiveText-LiveText3.14/src/classes/PostInstallHandlerTest.cls
@isTest
private class PostInstallHandlerTest {

    static testMethod void PostInstallHandler_Test() {

        PostInstallHandler postinstall = new PostInstallHandler();
        Test.testInstall(postinstall, null);
        LiveTextGlobalSettings__c ltgs = LiveTextGlobalSettings__c.getOrgDefaults();
        System.assertEquals(ltgs.GlobalTriggerExecutionEnabled__c, true, 'LiveTextGlobalSettings record created');
        List<String> pushTopicNames = new List<String>{constant.conversation_header_push_topic_Test, constant.sms_text_push_topic_Test};
        List<PushTopic> topic = [SELECT Id, Name FROM PushTopic WHERE Name IN:pushTopicNames];
        System.assertEquals(topic.size(), 2, 'PushTopic  found');
        ConfigurationSettings__c confSettings = ConfigurationSettings__c.getInstance(Constant.HEYWIRE_CONFIG);
        system.assert(confSettings != null);
    }

    static testMethod void UninstallScriptHandler_Test() {
        UninstallScriptHandler uninstall = new UninstallScriptHandler();
        Test.testUninstall(uninstall);
    }

    static testMethod void migrateNewTabSettings_Test(){
        Test.startTest();

        LiveText_Number__c l = new LiveText_Number__c();
        l.Show_New_Account_Tab__c = false;
        l.Show_New_Contact_Tab__c = true;
        l.Show_New_Lead_Tab__c = true;
        l.Show_New_Case_Tab__c = true;
        l.Show_New_Opportunity_Tab__c = true;
        l.Number__c = '1234567890';
        l.Name = 'testlabel';
        Insert l;
        PostInstallHandler postinstall = new PostInstallHandler();
        Test.testInstall(postinstall, new version(3,6),true);
        List<LiveText_Number__c> ltnObjects = Database.query('SELECT Id, Show_New_Account_Tab__c, Show_New_Contact_Tab__c, Show_New_Lead_Tab__c, Show_New_Case_Tab__c,Show_New_Opportunity_Tab__c, New_Custom_Objects_Tabs__c FROM LiveText_Number__c Where Show_New_Account_Tab__c=true OR Show_New_Contact_Tab__c=true OR Show_New_Lead_Tab__c=true OR Show_New_Case_Tab__c=true OR Show_New_Opportunity_Tab__c=true');
        system.assertEquals(ltnObjects[0].New_Custom_Objects_Tabs__c,'Contact;Lead;Case;Opportunity;');
        Test.stopTest();
    }

    static testMethod void setPhoneNumbersActivities_Test(){
        Test.startTest();
        LiveText_Number__c l = new LiveText_Number__c();
        l.CreateEvent__c = false;
        l.CreateTask__c = true;
        l.Number__c = '1234567890';
        l.Name = 'testlabel';
        Insert l;
        PostInstallHandler postinstall = new PostInstallHandler();
        Test.testInstall(postinstall, new version(3,4),true);
        List<LiveText_Number__c> ltnObjects = Database.query('SELECT Id, CreateEvent__c, CreateTask__c FROM LiveText_Number__c');
        system.assertEquals(ltnObjects[0].CreateEvent__c,false);
        system.assertEquals(ltnObjects[0].CreateTask__c,true);

        Test.stopTest();
    }
    
    
}