LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ConversationType__c</fullName>
        <label>ConversationType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number__c</fullName>
        <formula>IF((LEN(Formatted_Originating_Number_To_Display__c) = 0 || Formatted_Originating_Number_To_Display__c = null),  Originating_Number__c, Formatted_Originating_Number_To_Display__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Originating Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead lookup</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Number from which the SMS has been generated.</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support number that is LiveText enabled.</description>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number__c</fullName>
        <formula>IF(LEFT(Originating_Number__c,2)==&apos;+1&apos;, LEFT(Originating_Number__c, 2)+&apos; (&apos;+MID(Originating_Number__c,3,3)+&apos;) &apos;+MID(Originating_Number__c,6,3)+&apos;-&apos;+RIGHT(Originating_Number__c,4), &apos;+1&apos;+&apos; (&apos;+LEFT(Originating_Number__c,3)+&apos;) &apos;+MID(Originating_Number__c,4,3)+&apos;-&apos;+RIGHT(Originating_Number__c,4))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Originating Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/LiveTextController.cls
/**
 * @author         Santosh Gudge(santosh@comitydesigns.com)
 * @data           08.08.2014
 * @description    LiveTextController class contains methods used by the LiveText Chat Panel
 *                 in LiveText for Salesforce application.
 */
global with sharing class LiveTextController { 
	
	public Boolean isconversationEnded{get;set;}
    public SObject conversationHeader {get;set;}
	public String convHeaderStatus{get;set;}
    public String conversationRecordId {get;set;}
    public String originatingNumber {get;set;}
 	public List <Conversation_Header__c> ConversationHeaderList {get;set;}
 	public String  originatingObjectId{get;set;}
 	public String originatingObjectPrefix{get;set;}
      
    public String source {
        get {
            return constant.source_field;
        }
    }

    public String liveText {
        get {
            return constant.live_text;
        }
        set;
    }

    public String nameSpace {
        get {
            return util.getNamespace();
        }
        set;
    }
    
    public String userName {
        get {
            return string.valueOf(UserInfo.getName());
        }
        set;
    }

	public String ConversationHeaderRecords {
        get {
           return JSON.serialize(ConversationHeaderList);
        }
        set;
    }          

   /**
    * @description: Controller constructor method, used to intialize the collections, 
    *               variables and load the static data(like object prefixes) for the LiveText page.
    */ 
    public LiveTextController(ApexPages.StandardController stdController) {
        this.conversationHeader = stdController.getRecord();      
    }

	

    /**
     * @description: init method called when page loads to get initial message for auto response.
     */
    public void init() {
    	this.conversationRecordId = ApexPages.currentPage().getParameters().get('cvid');
    	this.originatingNumber = Apexpages.CurrentPage().getParameters().get('phone');
    	this.originatingObjectId = Apexpages.CurrentPage().getParameters().get('oid'); 
    	this.originatingObjectPrefix = Apexpages.CurrentPage().getParameters().get('objectprefix');
    	
    	   //check if there is any incoming conversation for this number
        if(originatingNumber != null && (conversationRecordId == 'null' || String.isBlank(conversationRecordId) || conversationRecordId == null)){
            String phoneNumber = originatingNumber.replaceAll('\\D', '');
            phoneNumber = (phoneNumber.startsWith('1')) ? 
                '+' + phoneNumber :
                '+1' + phoneNumber;
            List<Conversation_Header__c> conversations = [SELECT id FROM Conversation_Header__c WHERE Status__c = 'New' AND Originating_Number__c = :phoneNumber];
            if(!conversations.isEmpty()){
                this.conversationRecordId = conversations[0].id;
            }  
        }    	 
       
        // add check that conversationRecordId is of type Id
        ConversationHeaderList = [SELECT Id, Status__c, Support_Number__r.Number__c, Formatted_Originating_Number__c, 
        							Originating_Number__c, Lead__r.Name, Lead__c, Contact__r.Name, Contact__c, 
        							Case__r.CaseNumber, Case__c, Opportunity__r.Name, Opportunity__c 
        							FROM Conversation_Header__c 
        							WHERE Id=:conversationRecordId];
    
    	
        if(!ConversationHeaderList.isEmpty()){
	        convHeaderStatus = ConversationHeaderList.get(0).Status__c;
	        if (convHeaderStatus == constant.stage_ended) {
	        	isconversationEnded = true;
	        }
        }
        
  	
    }
                   
    public List<Conversation_Header__c> getCurrentConversationHeaderList() {
    	List<Conversation_Header__c> conversationHeaderList = [Select Id, Case__c, Support_Number__c,
    					Originating_Number__c,  ConversationType__c, Lead__c, Contact__c, Opportunity__c from Conversation_Header__c where id=: conversationRecordId limit 1];
    	return conversationHeaderList;
           			
    }  
    
    //@deprecated
    @RemoteAction
    global static String getMessagePayloadResponse(String message, Integer messageId, String conversationId, String originatingNumber, String supportNumber) {
    	return '';
    }
    
    @RemoteAction
    global static SMS_Text__c getSMSTextRecord(String smsTextRecord) {
    	return null;
    }
    
    @RemoteAction
    global static SMS_Text__c createSMSTextRecord(String message, String conversationId) {
        return null;
    }
    
	@RemoteAction
	global static String sendSMS2(SObject smsObject, String smsText){
		return null;
	}
    
}