LiveText-LiveText3.14/src/objects/Conversation_Header__c.object
<CustomObject>
    <description>LiveText Session</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ConversationType__c</fullName>
        <label>ConversationType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead lookup</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Number from which the SMS has been generated.</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support number that is LiveText enabled.</description>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveText Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveText Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveText Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LiveText</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/CommonTestHelper.cls
/*
* 
*   CommonTestHelper class provides help methods testing 
*   LiveText for Salesforce application
*
*   Author           |Author-Email                      |Date       |Comment
*   -----------------|----------------------------------|-----------|--------------------------------------------------
*   Santosh Gudge    |santosh@comitydesigns.com         |07.09.2014 |First draft
*
*/
 
public with sharing class CommonTestHelper {
    
    private static Account m_Account = null;  
    private static Contact m_Contact = null;  
    private static Case m_Case = null;  
    private static Lead m_Lead = null;
  
    /**
     * Retrieves the user with 'System Administrator' profile.
     * @return the User object with 'System Administrator' profile.
    */
    public static User GetTestRunAsUser() {    
        Profile p = [Select p.Name, p.Id From Profile p where p.Name =: Constant.system_administrator];
        User u = [select id, name from User where ProfileId = : p.id and IsActive = true][0]; 
        return u;
    }
    
    /** 
     * Comments 
     * Creates a Account.
     * @param Name - Name of Account
     * @return - New Account record that has or has not be saved the the database.
    */ 
    public static Account CreateAccount(String ActName) {
        Account objAccount = new Account();
        objAccount.Name = ActName;
        return objAccount;
    }
    
    /** 
     * Comments 
     *
     * Creates a lead.
     *
     * @param lastName - LastName of Contact
     * @param FirstName - FirstName of Contact
     * @return - New Contact record that has or has not be saved the the database.
    */
    public static Contact CreateContact(String Lastname, String FirstName) {
        Contact objContact = new Contact();
        objContact.Lastname = Lastname;
        objContact.FirstName = FirstName;
        return objContact;
    }
    
    /** 
     * Comments 
     * Creates a lead.
     * @param lastName - LastName of Lead
     * @param company - Company of Lead
     * @param status - Status of Lead
     * @return - New Lead record that has or has not be saved the the database.
    */
    public static Lead CreateLead(String lastName, String company, String status) {
        Lead objLead = new Lead();
        objLead.LastName = lastName;
        objLead.Company = company;
        objLead.Status = status;
        return objLead;
    }
  
    /*
     * Comments 
     * Creates a case.
     * @param status - Status of Case
     * @param origin - Origin of Case
     * @return - New Case record that has or has not be saved the the database.
    */
    public static Case CreateCase(String status, String origin) {
        Case objCase = new Case();
        objCase.Status = status;
        objCase.Origin = origin;
        return objCase;
    }
  
    /**
     * Retrieves the Conversation Header object. 
     *
     * @return the Conversation Header object without insert.
    */
    public static Conversation_Header__c CreateConversationHeader(String OriginatingNumber, String SupportNumber) {
        Conversation_Header__c conversationHeader = new Conversation_Header__c();
        m_Account = CreateAccount(Constant.accountName);
        insert m_Account;
        m_Case = CreateCase(Constant.stage_new,Constant.case_origin);
        insert m_Case;
        m_Lead = CreateLead(Constant.lastName, Constant.companyName, Constant.leadStatus);
        insert m_Lead;
        m_Contact = CreateContact(Constant.lastName, Constant.firstName);
        insert m_Contact;
        conversationHeader.Account__c = m_Account.Id;
        conversationHeader.Case__c = m_Case.Id;
        conversationHeader.Lead__c = m_Lead.Id;
        conversationHeader.Contact__c = m_Contact.Id;
        conversationHeader.Originating_Number__c = OriginatingNumber;
        conversationHeader.Support_Number__c = SupportNumber;
        conversationHeader.Status__c = Constant.stage_new;
        conversationHeader.ConversationType__c = Constant.ConversationType.Inbound.name();
        return conversationHeader;
    } 
    
    /**
     * Retrieves the SMS_Text__c object. 
     * @return the SMS_Text__c object without insert.
    */
    public static SMS_Text__c CreateSMSTextRecord (String OriginatingNumber, String SupportNumber, String conversationHeaderId) {
        SMS_Text__c SMSText = new SMS_Text__c();
        if (conversationHeaderId != null) {
            SMSText.Conversation_Header__c = conversationHeaderId;
        }
        SMSText.Originating_Number__c = OriginatingNumber;
        SMSText.Support_Number__c = SupportNumber;
        SMSText.Source__c = Constant.live_text;
        return SMSText;
    }
}