LiveText-LiveText3.14/src/objects/ITR_Message__c.object
<CustomObject>
    <description>Inbound Messages for ITR</description>
    <fields>
        <fullName>Available_Agents__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Agents</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Formatted_Originating_Number__c</fullName>
        <formula>Originating_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Originating Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITR_Context__c</fullName>
        <description>Context for this ITR interaction</description>
        <label>ITR Context</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Within_Business_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the current message was received during business hours</description>
        <label>Is Within Business Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>LiveText Number associated with this interaction</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>ITR Messages</relationshipLabel>
        <relationshipName>ITR_Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mo_Message_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MO Message Counter is incremented by 1 every time a Mobile Originated message is received by the ITR.</description>
        <inlineHelpText>MO Message Counter is incremented by 1 every time a Mobile Originated message is received by the ITR.</inlineHelpText>
        <label>Mo Message Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating phone number for this interaction</description>
        <label>Originating Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Omni-Channel Queue to route this interaction to</description>
        <label>Queue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ITR Message</label>
    <nameField>
        <label>ITR Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITR Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/UpdateITRMessageAction.cls
/**
 * @description:    This class updates the given entries in ITR_Message.
*/
global class UpdateITRMessageAction{

    /**
     * @description Updates the given entries in ITR_Message. 
     *  
     * @Param       List of entries to update.
     *
     * @Return      LiveText_ActionResult records for each item.
     **/ 
    @InvocableMethod(label='Update ITR Message' description='Updates the given entries in ITR_Message__c')
    global static  List<ActionResult> updateITRMessages(List<UpdateInboundItem> items) {
        
        List<ActionResult> results = new List<ActionResult>();
           
        for (UpdateInboundItem item : items) {
            results.add(updateITRMessage(item));
        }
        return results;  
    }
    
    public static ActionResult updateITRMessage(updateInboundItem item) {
        
        ActionResult result = new ActionResult(item.ObjectId);       
        List<ITR_Message__c> msgList = [SELECT Id, LiveText_Number__c, Originating_Number__c, ITR_Context__c, Queue_Name__c,
                                            Is_Within_Business_Hours__c, Available_Agents__c, Mo_Message_Counter__c
                                        FROM ITR_Message__c 
                                        WHERE Id =: item.ObjectId];
        if(msgList.size() == 0){
            result.setError('Item does not exist.');
            return result;
        }else{
            Map<Id, Set<Id>> ltNumberToAvaliableAgentsMap = Util.getAvailableAgentsMap();

            PhoneNumberRelatedObjects relatedObjects = null;
            ITR_Message__c msg = (msgList.size() > 0) ? msgList[0] : null;
            try{
                String  formattedOriginatingNumber = msg.Formatted_Originating_Number__c.subString(msg.Formatted_Originating_Number__c.indexOf('('));
                relatedObjects = new PhoneNumberRelatedObjects(msg.LiveText_Number__c, formattedOriginatingNumber);
            }catch(Exception ex){
                Util.insertException('updateITRMessages', constant.priority_high, ex.getMessage());
            } 
            if (msg != null) {
                if(item.QueueName != null){
                    msg.Queue_Name__c = item.QueueName;
                }
                if(item.ITRContext != null){
                    msg.ITR_Context__c = item.ITRContext;
                }
                if(relatedObjects != null) {
                    try{
                        if(relatedObjects.HasItems){
                            Map<String, String> relationshipObjectApiNameToFieldNameMap = new Map<String, String>();
                            Map<String, Schema.SObjectField> fieldMap = msg.getSObjectType().getDescribe().fields.getMap();
                            for(String field : fieldMap.keySet()){
                                if(fieldMap.get(field).getDescribe().getRelationshipName() != null && fieldMap.get(field).getDescribe().isCustom()){
                                    relationshipObjectApiNameToFieldNameMap.put(fieldMap.get(field).getDescribe().getReferenceTo().get(0).getDescribe().getName(), field);
                                }
                            }
                            for(String relationshipName : Util.getAllRelationshipObjects(msg.getSObjectType().getDescribe().getName())){
                                msg.put(relationshipObjectApiNameToFieldNameMap.get(relationshipName), PhoneNumberRelatedObjects.getMRMItem(relatedObjects.CustomObjects, msg.getSObjectType().getDescribe().fields.getMap().get(relationshipObjectApiNameToFieldNameMap.get(relationshipName)).getDescribe().getReferenceTo().get(0).getDescribe().getName()));
                            }
                        }
                    }catch(Exception ex){
                        Util.insertException('updateITRMessages', constant.priority_high, ex.getMessage());
                    }
                }
                if(msg.Mo_Message_Counter__c == null){
                    msg.Mo_Message_Counter__c = 0;
                }
                msg.Mo_Message_Counter__c = msg.Mo_Message_Counter__c+1;
                List<Id> temp = new List<Id>();
                if(ltNumberToAvaliableAgentsMap.containsKey((Id) msg.LiveText_Number__c)){
                    temp.addAll(ltNumberToAvaliableAgentsMap.get((Id) msg.LiveText_Number__c));
                }
                msg.Available_Agents__c = temp.size();   
                AccessController.updateAsSystem(new list <ITR_Message__c>{msg});                
            } 
        }
        return result;
    }
}