LiveText-LiveText3.14/src/objects/ITR_Message__c.object
<CustomObject>
    <description>Inbound Messages for ITR</description>
    <fields>
        <fullName>HTML_Transcript__c</fullName>
        <description>HTML transcript for this interaction</description>
        <label>HTML Transcript</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Within_Business_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the current message was received during business hours</description>
        <label>Is Within Business Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>LiveText Number associated with this interaction</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>ITR Messages</relationshipLabel>
        <relationshipName>ITR_Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Number__c</fullName>
        <description>Originating phone number for this interaction</description>
        <label>Originating Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Transcript__c</fullName>
        <description>Text transcript for this interaction</description>
        <label>Text Transcript</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ITR Message</label>
    <nameField>
        <label>ITR Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ITR Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/UpdateITRMessageActionTest.cls
@isTest
public with sharing class UpdateITRMessageActionTest { 
    static List<UpdateInboundItem> items;
    static LiveText_Number__c ltNumberObj;
    static ITR_Message__c msg;
    static Contact ct;
    static User adminUser;
    
    static void createAdminUser(){
        adminUser = UnitTestObjectBuilder.createAdminUser();
        insert adminUser;
    }
    
    static testmethod void initTestData(){ 
        
        ltNumberObj = UnitTestObjectBuilder.createLiveTextNumber();
        ltNumberObj.Number__c = Util.NormalizePhoneNumber(ltNumberObj.Number__c);
        insert ltNumberObj;
         
        ct = new Contact(LastName='John',FirstName='John',mobilephone = '+1 (212) 555-1212');
        insert ct;

        msg = new ITR_Message__c();
        msg.Originating_Number__c = '+1 (212) 555-1212';
        msg.LiveText_Number__c = ltNumberObj.Id;
        msg.Is_Within_Business_Hours__c = false;
        msg.HTML_Transcript__c = '';
        msg.Text_Transcript__c = '';        
        insert msg;

        
        items = new List<UpdateInboundItem>();
        UpdateInboundItem item = new UpdateInboundItem();
        item.ObjectId = msg.Id;
        item.QueueName = 'testQueue';
        item.ITRContext = 'sales';
        items.add(item);
    }
  
    static testMethod void Test_UpdateITRMessageAction(){
        createAdminUser();
        system.runAs(adminUser){
            Test.startTest();
            initTestData();
            UpdateITRMessageAction.updateITRMessages(items);
            Test.stopTest();
        }
    }
  
    
}