LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/ScreenPopSequence__c.object
<CustomObject>
    <description>The order that LiveText will pop records to LiveText agents after an inbound text is accepted.</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Live Text Phone Number</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>ScreenPopSequence</relationshipLabel>
        <relationshipName>ScreenPopSequence</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>Record Type (Account, Contact, Lead, etc.)</description>
        <label>Record Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Screen Pop Sequence</label>
    <nameField>
        <label>ScreenPopSequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Pop Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/AssignScreenPopRecordTypeHelperTest.cls
@isTest
public with sharing class AssignScreenPopRecordTypeHelperTest {
    static SObject ltnObject;
    static String searchText;
    static Set<String> availableRecordTypeList;
    static Set<String> selectedRecordTypeList;
    static User adminUser;
    static String CaseObjectName;
    static String LeadObjectName;
    static String AccountObjectName;
    static String ContactObjectName;
    static String OpportunityObjectName; 
    
    static void createAdminUser() {
        adminUser = UnitTestObjectBuilder.createAdminUser();
        insert adminUser;
    }

    static void initTestData() {
        ltnObject = UnitTestObjectBuilder.createLiveTextNumber();
        insert ltnObject;
        CaseObjectName = Util.GLOBAL_DESCRIBE.get(Constant.CASE_OBJECT).getDescribe().getName();
        LeadObjectName = Util.GLOBAL_DESCRIBE.get(Constant.LEAD_OBJECT).getDescribe().getName();
        AccountObjectName = Util.GLOBAL_DESCRIBE.get(Constant.ACCOUNT_OBJECT).getDescribe().getName();
        ContactObjectName = Util.GLOBAL_DESCRIBE.get(Constant.CONTACT_OBJECT).getDescribe().getName();
        OpportunityObjectName = Util.GLOBAL_DESCRIBE.get(Constant.OPPORTUNITY_OBJECT).getDescribe().getName();
        availableRecordTypeList = new Set<String>();
        selectedRecordTypeList = new Set<String>();
        selectedRecordTypeList.add(CaseObjectName);
        availableRecordTypeList.add(CaseObjectName);
        selectedRecordTypeList.add(LeadObjectName);
        availableRecordTypeList.add(LeadObjectName);
        selectedRecordTypeList.add(AccountObjectName);
        availableRecordTypeList.add(AccountObjectName);
        selectedRecordTypeList.add(ContactObjectName);
        availableRecordTypeList.add(ContactObjectName);
        selectedRecordTypeList.add(OpportunityObjectName);
        availableRecordTypeList.add(OpportunityObjectName);
        ScreenPopSequence__c seq1 = UnitTestObjectBuilder.createScreenPopSequence(ltnObject.Id,LeadObjectName,1);
        insert seq1;
        ScreenPopSequence__c seq2 = UnitTestObjectBuilder.createScreenPopSequence(ltnObject.Id,CaseObjectName,2);
        insert seq2;
    }

    static testMethod void Test_GetSelectedRecordTypes_Positive() {
        createAdminUser();
        system.runAs(adminUser) {
            Test.startTest();
            initTestData();
            AssignScreenPopRecordTypeHelper helper = new AssignScreenPopRecordTypeHelper(ltnObject);
            List<SelectOption> selectedMembers = helper.getSelectedRecordTypes();
            system.assert(selectedMembers != null);
            system.assert(!selectedMembers.isEmpty());
            Test.stopTest();
        }
    }
        
    static testMethod void Test_RemoveAddRecordTypes() {
        createAdminUser();
        system.runAs(adminUser) {
            Test.startTest();
            initTestData();
            LiveText_Number__c newLtnObject = UnitTestObjectBuilder.createLiveTextNumber();
            insert newLtnObject;
            AssignScreenPopRecordTypeHelper helper = new AssignScreenPopRecordTypeHelper(newLtnObject);
            helper.removeAddRecordTypes(selectedRecordTypeList);
            List<ScreenPopSequence__c> seqs =  [    Select Record_Type__c, LiveText_Number__c
                                                    From ScreenPopSequence__c 
                                                    Where LiveText_Number__c=:ltnObject.Id Order By Sequence__c
                                                ];
            system.assert(seqs != null);
            system.assert(!seqs.isEmpty());
            system.assertEquals(seqs.get(0).LiveText_Number__c, ltnObject.Id);
            Test.stopTest();
        }
    }   
}