LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Schedule__c.object
<CustomObject>
    <description>Object for sending out a scheduled SMS</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact that generated this SMS</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Lead that generated this SMS</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The LiveText number to send the SMS from.</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>SMS Message to send</description>
        <label>Message</label>
        <length>480</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The Id of the object that generated this SMS</description>
        <label>Object Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Unique Identifier for the flow related to this SMS</description>
        <label>Reference Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <description>The date and time to send this SMS</description>
        <label>Schedule Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>To_Phone_Number__c</fullName>
        <description>The phone number to send the SMS to</description>
        <label>To Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>SMS Schedule</label>
    <nameField>
        <label>SMS Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/DeleteMessageActionTest.cls
@isTest
public with sharing class DeleteMessageActionTest {

    static Contact conObj;
    static Account accObj;
    static Lead leadObj;
    static LiveText_Number__c ltNumberObj;
    static SMS_Schedule__c smsScheduleObj;
    
    static testmethod void setUp() {
        conObj = new Contact(LastName='John',FirstName='John');
        conObj.mobilephone = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        insert conObj;
        accObj = new Account(Name='Test Acc Name');
        accObj.phone = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        insert accObj;
        leadObj = new Lead(LastName='Test Lead Last Name',company='Test Lead Company');
        leadObj.phone = UnitTestObjectBuilder.GenerateValidFormattedPhoneNumber();
        insert leadObj;
        ltNumberObj = UnitTestObjectBuilder.createLiveTextNumber();

        ltNumberObj.Number__c = Util.NormalizePhoneNumber(ltNumberObj.Number__c);
        
        insert ltNumberObj;
        
        smsScheduleObj = new SMS_Schedule__c();
        smsScheduleObj.Contact__c = conObj.id;
        smsScheduleObj.Lead__c = leadObj.id;
        smsScheduleObj.LiveText_Number__c = ltNumberObj.id;
        smsScheduleObj.Message__c = 'Test Message';
        smsScheduleObj.Object_Id__c = accObj.id;
        smsScheduleObj.Reference_Id__c = '00Qj000000Ja9nqEAC';
        Datetime myDT = Datetime.now();
        smsScheduleObj.Schedule_Date__c = myDT.addDays(1);
        smsScheduleObj.To_Phone_Number__c = UnitTestObjectBuilder.GenerateValidPhoneNumber();
        insert smsScheduleObj;
    }
    
    static testMethod void DeleteMessages_Test() {
        setUp();
        Test.startTest();
        DeleteSmsScheduleItem delSchItemObj = new DeleteSmsScheduleItem();
        delSchItemObj.ObjectId = accObj.id;
        delSchItemObj.ReferenceId = '00Qj000000Ja9nqEAC';
        
        List<ActionResult> results;
        
        results = DeleteMessageAction.DeleteSmsScheduleMessages(new List<DeleteSmsScheduleItem>{delSchItemObj});
        
        System.assert(!results.isEmpty());
        
        Test.stopTest();
    }
    
}