LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <fields>
        <fullName>Number__c</fullName>
        <description>LiveText Number</description>
        <inlineHelpText>The phone number / shortcode that has been verified and enabled for LiveText. To register additional phone numbers please contact LiveText support at http://support.hwlivetext.com</inlineHelpText>
        <label>Support Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/OptInStatus__c.object
<CustomObject>
    <description>Opt-in status for a given phone number. The status regards communication between the relevant LiveText phone number and the given phone number.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>The opt-in status of the subscriber. 1 = opted in, 0 = opted out</description>
        <label>Status</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opt-In Status</label>
    <nameField>
        <label>OptInStatus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opt-In Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Message__c.object
<CustomObject>
    <description>An SMS message</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to this message</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SMS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to this message</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SMS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnforceObjectPresence__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked and the object specified by ObjectId is is deleted, the send will fail.</description>
        <label>EnforceObjectPresence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead related to this message</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>SMS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Live Text number to send this message from</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>SMS_Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Status__c</fullName>
        <description>Status of the message</description>
        <label>Message Status</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to send</description>
        <label>Message</label>
        <length>2350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>Id of the object related to this message</description>
        <label>Object Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opt_in_Status__c</fullName>
        <description>Opt-in status of the subscriber at the time of sending the message</description>
        <label>Opt-in Status</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>To_Phone_Number__c</fullName>
        <description>Phone number to send the message to</description>
        <label>To Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <label>SMS Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/SMS_Schedule__c.object
<CustomObject>
    <description>Object for sending out a scheduled SMS</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related account object that generated this SMS</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact that generated this SMS</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnforceObjectPresence__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked and the object specified by ObjectId is is deleted, the send will fail.</description>
        <label>EnforceObjectPresence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Lead that generated this SMS</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The LiveText number to send the SMS from.</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipName>SMS_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>SMS Message to send</description>
        <label>Message</label>
        <length>480</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The Id of the object that generated this SMS</description>
        <label>Object Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Unique Identifier for the flow related to this SMS</description>
        <label>Reference Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <description>The date and time to send this SMS</description>
        <label>Schedule Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>To_Phone_Number__c</fullName>
        <description>The phone number to send the SMS to</description>
        <label>To Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>SMS Schedule</label>
    <nameField>
        <label>SMS Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/QueueMessageAction.cls
/**
 * @description:    QueueMessageAction is used to queue a previously scheduled item for immediate delivery.
 *                  Queueing entails inserting the scheduled item into the SMS_Message table. 
 *                  This subsequently triggers a workflow that determines whether or not to actually send
 *                  the message. 
 */
 global class QueueMessageAction {
    
     /**
     * @description Queues the given scheduled items for immediate delivery and returns the status of each item.
      *     
     * @Param       List of scheduled items to queue for delivery.
     *
     * @Return      LiveText_ActionResult records for each item.
     **/ 
    @InvocableMethod(label='Queue Messages' description='Queues the given messages for delivery and returns the status of each item.')
    global static  List<ActionResult> queueMessages(List<QueueItemRequest> items) {
        List<ActionResult> results = new List<ActionResult>();
        results = queueMessage(items);
        return results;  
    }
      
     /**
     * @description Queues the given scheduled item for immediate delivery and returns the status of the item.
      *     
     * @Param       Scheduled item to queue for delivery.
     *
     * @Return      Results of queueing this item.
     **/   
    public static List<ActionResult> queueMessage(List<QueueItemRequest> requestItems) {
       List<ActionResult> results = new List<ActionResult>();
        List<Id> ids = new List<Id>();
        List<Id> liveTextNumbers = new List<Id>();
        List<SMS_Schedule__c> toPhoneNumbers = new List<SMS_Schedule__c>();
        for(QueueItemRequest requestItem :requestItems){
            ActionResult result = new ActionResult(requestItem.ScheduledItemId);
            if(requestItem == null){
                result.setError('Item does not exist.');
                results.add(result);
                return results;
            }
            ids.add(requestItem.ScheduledItemId);
            results.add(result);
        }
        
        
        List<SMS_Schedule__c> scheduleList = getScheduledItemList(ids);
        
        // retrieve current opt-in status between these 2 phone numbers
        Map<String,Decimal> optInStatusMap = Util.getOptInStatus(scheduleList);
        // Insert into SMS_Message table which will trigger a workflow to determine whether or not to actually send the message.

        List<SMS_Message__c> messagesList = new List<SMS_Message__c>();
        for(SMS_Schedule__c schedule : scheduleList){
            //LiveText_Number__c liveTextNumber = schedule.LiveText_Number__r;
            Decimal optInStatus = null;
            if(optInStatusMap!=null){
                optInStatus = optInStatusMap.get(Util.NormalizePhoneNumber(schedule.LiveText_Number__r.Number__c) + '->' + Util.NormalizePhoneNumber(schedule.To_Phone_Number__c));
            }
            SMS_Message__c message = new  SMS_Message__c(Account__c = schedule.Account__c,
                Contact__c = schedule.Contact__c,
                Lead__c = schedule.Lead__c,
                LiveText_Number__c = schedule.LiveText_Number__c,
                Message__c = schedule.Message__c,
                Object_Id__c = schedule.Object_Id__c,
                Opt_in_Status__c = (optInStatus == null) ? null : optInStatus,
                To_Phone_Number__c = schedule.To_Phone_Number__c,
                Message_Status__c = 'Queued',
                EnforceObjectPresence__c =  schedule.EnforceObjectPresence__c ); 
            messagesList.add(message);
        }
        AccessController.insertAsSystem(messagesList);
        return results;
    
    }
    
     /**
     * @description Queues the given scheduled item for immediate delivery and returns the status of the item.
     *  
     * @Param       Scheduled item to queue for delivery.
     *
     * @Return      Results of queueing this item.
     **/   
    public static ActionResult queueItem(ScheduleItem item) {
       
        if(item == null) return null;
        
        ActionResult result = new ActionResult(item.ObjectId);
        String normalizedToNumber = Util.NormalizePhoneNumber(item.ToPhoneNumber);
        
        // retrieve current opt-in status between these 2 phone numbers
        OptInStatus__c optInStatus =  Util.getOptInStatus(item.LiveTextPhoneNumber.Id, item.ToPhoneNumber);
 
        // Insert into SMS_Message table which will trigger a workflow to determine whether or not to actually send the message.
        //-V- ScheduleItem refactor place
        SMS_Message__c message = new  SMS_Message__c(   Account__c = item.AccountId,
                                                        Contact__c = item.ContactId,
                                                        Lead__c = item.LeadId,
                                                        LiveText_Number__c = item.LiveTextPhoneNumber.Id,
                                                        Message__c = item.Message,
                                                        Object_Id__c = item.ObjectId,
                                                        Opt_in_Status__c = (optInStatus == null) ? null : optInStatus.Status__c,
                                                        To_Phone_Number__c = normalizedToNumber,
                                                        Message_Status__c = 'Queued',
                                                        EnforceObjectPresence__c = false //item.EnforceObjectPresence
                                                      );
        AccessController.insertAsSystem(new list < SMS_Message__c >{message});
        
        return result;
    
    }
    
    
    /**
     * @description Retrieves the given scheduled item from the SMS_Schedule table.
     *  
     * @Param       Id of item to retrieve.
     *
     * @Return      SMS_Schedule__c item or null if not found.
     **/ 
     @TestVisible  
     private static SMS_Schedule__c getScheduledItem(ID id){
        SMS_Schedule__c[] schedules = 
            [SELECT Account__c, Contact__c, CreatedById, CreatedDate, IsDeleted, LastModifiedById, LastModifiedDate, 
            Lead__c, LiveText_Number__c,LiveText_Number__r.Number__c,Message__c, Object_Id__c, OwnerId, Id, Reference_Id__c, Name, 
            Schedule_Date__c, SystemModstamp, To_Phone_Number__c, EnforceObjectPresence__c From SMS_Schedule__c Where ID=:id];          
        if(schedules.size() > 0){
            return schedules[0];
        }
        return null;
    }

    @TestVisible  
     private static List<SMS_Schedule__c> getScheduledItemList(List<ID> ids){
        List<SMS_Schedule__c> schedules = 
            [SELECT Account__c, Contact__c, CreatedById, CreatedDate, IsDeleted, LastModifiedById, LastModifiedDate, 
            Lead__c, LiveText_Number__c,LiveText_Number__r.Number__c,Message__c, Object_Id__c, OwnerId, Id, Reference_Id__c, Name, 
            Schedule_Date__c, SystemModstamp, To_Phone_Number__c, EnforceObjectPresence__c From SMS_Schedule__c Where ID IN :ids];          
        if(schedules!=null){
            return schedules;
        }
        return null;
    }
}