LiveText-LiveText3.14/src/objects/LiveText_Number__c.object
<CustomObject>
    <description>LiveText Number</description>
    <label>LiveText Number</label>
    <nameField>
        <label>Phone Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LiveText Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/objects/ScreenPopSequence__c.object
<CustomObject>
    <description>The order that LiveText will pop records to LiveText agents after an inbound text is accepted.</description>
    <fields>
        <fullName>LiveText_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Live Text Phone Number</description>
        <label>LiveText Number</label>
        <referenceTo>LiveText_Number__c</referenceTo>
        <relationshipLabel>ScreenPopSequence</relationshipLabel>
        <relationshipName>ScreenPopSequence</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>Record Type (Account, Contact, Lead, etc.)</description>
        <label>Record Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Screen Pop Sequence</label>
    <nameField>
        <label>ScreenPopSequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Pop Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LiveText-LiveText3.14/src/classes/AssignScreenPopRecordTypeHelper.cls
/**
 * @author         Fitzroy Robertson
 * @version        1.0
 * @date           07.28.2015
 * @description    This is helper class for Assign Screen pop Record Type functionality on the admin page. It contain methods to perform followin functionalities, 
 *                 1. Retrieves the already associated record types with the LiveText Number.
 *                 2. Removes the Record Types provided in available record types list.
 *                 3. Adds the Record Types provided in selected record types list.
 *  
*/
public with sharing class AssignScreenPopRecordTypeHelper {
    private SObject ltnObject;  
    /**
     * @description: Constructor method, used to intialize the LiveText Number Object, object name. 
     * @param: LiveText Number Object.
    */  
    public AssignScreenPopRecordTypeHelper(SObject ltnObject) {
        this.ltnObject = ltnObject;
    }
    
    /**
     * @description: Retrieves the list of record types already associated with a given LiveText Number object.
     * @return List of SelectOption object, which is displayed in selected member list.
    */
    public List<SelectOption> getSelectedRecordTypes() {
        List<SelectOption> selectedRecordTypes = new List<SelectOption>();
        if(ltnObject != null && ltnObject.Id != null) {
            List<ScreenPopSequence__c> associatedRecordTypesList = retrieveAssociatedRecordTypes();
            if(associatedRecordTypesList != null && !associatedRecordTypesList.isEmpty()) {
                for(ScreenPopSequence__c sequence : associatedRecordTypesList) {
                    String recordType = sequence.Record_Type__c;
                    selectedRecordTypes.add(new SelectOption(recordType, Schema.describeSObjects(new List<String>{recordType})[0].getLabel()));
                }
            }
        }
        return selectedRecordTypes;
    }
    
    /**
     * @description: Removes the record types given in the selected record types list and adds the record types given in the available list.
     * @param: selectedRecordTypesList, set of selected record types to be removed.
    */
    public void removeAddRecordTypes(Set<String> selectedRecordTypesList) {
        removeRecordTypes();
        addRecordTypes(selectedRecordTypesList);
    }
    
    private void removeRecordTypes() {
        List<ScreenPopSequence__c> associatedRecordTypesList = retrieveAssociatedRecordTypes();
        if(associatedRecordTypesList != null && !associatedRecordTypesList.isEmpty()) {
            AccessController.deleteAsUser(associatedRecordTypesList);
        }
    }
    
    private void addRecordTypes(Set<String> selectedRecordTypesList) {
        List<ScreenPopSequence__c> addRecordTypeList = new List<ScreenPopSequence__c>();
        Integer sequenceOrder = 1;
        for(String recordType : selectedRecordTypesList) {
            addRecordTypeList.add(createScreenPopSequence(recordType, sequenceOrder));
            sequenceOrder++;
        }
        if(!addRecordTypeList.isEmpty()) {
            AccessController.insertAsUser(addRecordTypeList);
        }
    }
    
    private ScreenPopSequence__c createScreenPopSequence(String recordType, Integer sequenceOrder) {
        ScreenPopSequence__c sequence = new ScreenPopSequence__c();
        sequence.LiveText_Number__c = this.ltnObject.Id;
        sequence.Record_Type__c = recordType;
        sequence.Sequence__c = sequenceOrder;
        return sequence;
    }
 
    /**
     * @description: Retrieves the record types for the given Live Text Number 
    */   
    private List<ScreenPopSequence__c> retrieveAssociatedRecordTypes() { 
        Set<String> linkedObjects = Util.getAllRelationshipObjects();
        return [    Select Record_Type__c 
                    From ScreenPopSequence__c 
                    Where LiveText_Number__c=:this.ltnObject.Id 
                    AND Record_Type__c IN :linkedObjects
                    Order By Sequence__c
                ];
    }   
}